### ISSUE TITLE
WIP (Work In Progress) の GitHub アプリを導入しませんか?

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/management-forum#16]
WIP (Work In Progress) の GitHub アプリを導入しませんか?

'Work In Progress'

- https://blog.github.com/2018-07-10-optimizing-open-source-projects-with-github-apps/
- https://probot.github.io/apps/wip/

これを設定するとタイトルに WIP がついた PR のマージをブロックできます。
タイトルから WIP を取るとマージのブロックを解除できます。

※ 自分のアカウントのリポジトリに対して試して動くのは確認できました。
sakura-editor/sandbox で設定しようとしましたが、権限がないのかわからないですが、
設定できませんでした。

※ 別件ですが、上記の github の blog に Welcome というアプリも紹介されています。
初めて PR や issue 等を作成した人に対して Welcome メッセージを
自動で入れるアプリのようです。試してはいないです。

**Comment by kobake** [comment]
うーん、個人的には運用でカバーできるところは無理にツール入れなくても良いかな、と思っていますが、手間でなければ入れてもらっても良いです。

> sakura-editor/sandbox

これについては sakura-developers チームに admin 権限付けてるんですけどね…。条件よくわからないです。

**Comment by m-tmatma** [comment]
導入できました。
https://github.com/sakura-editor/sandbox/pull/1

既存の PR には適用できないみたいです。

**Comment by m-tmatma** [comment]
https://github.com/sakura-editor/sakura/pull/254 で動くのを確認しました。
