### ISSUE TITLE
googletest をfork しませんか？

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/management-forum#17]
https://github.com/google/googletest/pull/1606
で PR 投げてますが、完全に無視されています。

なのでいつまでたっても以下の対応が出来ません
https://github.com/sakura-editor/sakura/issues/181

googletest 本体の対応を待つのは諦めて fork したバージョンを使いますか？

**Comment by berryzplus** [comment]
forkしてしまうのも1つの案ですね・・・
#10 に現状わかっていることをまとめてみようと思います。

**Comment by berryzplus** [comment]
ローカルで検証してみたところ、
@m-tmatma さんのコミットは「マージコミットです」と言われます。

[Fix warning C4819 in Visual Studio  #1668](https://github.com/google/googletest/pull/1668) (Merged)

ほぼ同内容の変更がマージされたことを考えると、
マージコミットになってるのが取り込まれない原因なんではないかと予想します。

masterでビルドNGになったappveyor画面と
コミット適用後OKになったappveyor画面を見せれば
さすがに通るだろう、と思って作業したんですよ・・・。
https://ci.appveyor.com/project/berryzplus/googletest/build/1

いちおうNG画面は想定通り、SystemLocaleをja-JPに変えただけで簡単に再現しました。
テストブランチに https://github.com/google/googletest/pull/1606 をチェリーピックしようとして気付きました。

**Comment by berryzplus** [comment]
別案投下してきました。
いい加減そろそろ、テスト構成の話を始めたい感じです・・・。

**Comment by berryzplus** [comment]
で、やっぱり反応なしって言うね…

**Comment by kobake** [comment]
これ以上待ってるのも不毛なので一旦 fork 版使うのが良いと思います。
sakura-editor 配下に fork します？

**Comment by m-tmatma** [comment]
はい、いいと思います

**Comment by kobake** [comment]
fork しちゃいました。
https://github.com/sakura-editor/googletest

@sakura-editor/sakura-developers に Admin 権限付けてます。

ここうまく使っていきましょう。

**Comment by m-tmatma** [comment]
参考情報
https://rcmdnk.com/blog/2017/08/29/computer-github/

**Comment by kobake** [comment]
なるほど。Issues も有効にしておきました。

**Comment by m-tmatma** [comment]
#18 を作成しました。

**Comment by berryzplus** [comment]
マージされましたねｗ
