### ISSUE TITLE
googletest の fork の運用方法を検討する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/management-forum#18]
googletest の fork の運用方法を検討する

- ブランチの保護設定
- ブランチの運用ルール、本家との同期

など

**Comment by kobake** [comment]
あまりガッツリいじる想定は考えてないです。少なくともブランチの保護までは必要ないかな、と思っています。

たぶんですけど @m-tmatma さんが主にいじることになる気がするので、他の方から異論なければ独断で進めてしまっても良いのではないかと。

**Comment by berryzplus** [comment]
こっに移動してましたか・・・
@m-tmatmaさんのPRがマージされました。
現状で、SystemLocaleが日本語でもビルドが通る状態に戻ったはずです。

**Comment by m-tmatma** [comment]
同期する PR を作成しました。
https://github.com/sakura-editor/googletest/pull/1

**Comment by m-tmatma** [comment]
どうしよう、本家を使うか、fork を使うか

**Comment by berryzplus** [comment]
よくよく考えたら上位のcmakelist.txtから/utf-8を指定してしまえば済む話だったような…

サクラエディタ本体のビルド環境を変更するのは依然反対ですが、テスト環境はcmakeがいいと思っています。

**Comment by kobake** [comment]
あら、入れ違いになりましたね。本家で済むなら本家使うのが無難かな、と。

**Comment by m-tmatma** [comment]
そうですね。
本家が対応してくれない問題が発生したときに考えたらいいですね。

**Comment by m-tmatma** [comment]
マージされたのに閉じてなかった。
