### ISSUE TITLE
OSDNの「開発・管理」フォーラムを閉鎖することを考えています

### ISSUE THREAD

**Issue by kobake** [sakura-editor/management-forum#2]
以下、OSDNの「開発・管理」フォーラムを閉鎖しようと思います。
https://osdn.net/projects/sakura-editor/forums/34093/

経緯としては「匿名投稿可能な場が欲しい」という声があったためOSDNフォーラムを作りましたが、開発者（兼・運用管理者）の発言は現状 GitHub 側にほぼほぼ集約されているようですので、OSDN側の「開発・管理」フォーラムを残す価値は無いと考えています。

閉鎖する場合、内容のバックアップを GitHub Pages のどこかにでもアップロードしておくつもりです。

何かご意見あればください。
2018-06-24 00:00 JST までに集まった意見をもとに最終的な判断を行いたいと思います。

**Comment by KENCHjp** [comment]
消したいです。

**Comment by kobake** [comment]
異論も無いようですし、OSDNの「開発・管理」フォーラムを閉鎖します。
閉鎖のアナウンスを OSDN 側に流しました。
https://osdn.net/projects/sakura-editor/forums/34093/39712/

閉鎖前に該当フォーラムのバックアップをとり、Web 領域からログは見れるようにしておきます。

**Comment by kobake** [comment]
該当フォーラムのバックアップを https://github.com/sakura-editor/sakura-editor.github.io/pull/31 で対応しました。これがマージされたら該当フォーラムは閉鎖（削除）し、本 Issue をクローズします。

**Comment by kobake** [comment]
sakura-editor/sakura-editor.github.io#31 対応完了。
ちょっと所用があるので後で OSDN の該当フォーラムのほう削除しておきます。

**Comment by KENCHjp** [comment]
やっときまーす。

**Comment by kobake** [comment]
ありがとうございます（｀ェ´）ピャー

**Comment by KENCHjp** [comment]
クローズします。

**Comment by kobake** [comment]
消えてること確認しました！ご対応ありがとうございました！ :pray:
