### ISSUE TITLE
OSDNでTwitter連携ためしてみました

### ISSUE THREAD

**Issue by KENCHjp** [sakura-editor/management-forum#21]
でも、URL付きのつぶやきは、ハッシュタグでは検索できない罠。
そのアカウントが信頼されないと？、スパム判定されるみたいで、
アカウントのフォロアー以外からは見つけてもらえないみたいです。
OSDNの活動をツィートしても、#サクラエディタ みたいなハッシュタグで検索している人へはアピれないみたい。

**Comment by kobake** [comment]
https://twitter.com/search?f=tweets&vertical=default&q=%23%E3%82%B5%E3%82%AF%E3%83%A9%E3%82%A8%E3%83%87%E3%82%A3%E3%82%BF&src=typd

自分が試した感じだと、フォロワーでもフォロイーでもない人の発言で URL 付きのものも引っかかりますけど、そのアカウントが信頼されている（？）から？ですかね？？

**Comment by KENCHjp** [comment]
>そのアカウントが信頼されている（？）から？ですかね？？

まじすか。。。
うーん、俺、信頼無い、、、、、、、、

ちゃんと調べたっすよ、URL付きつぶやきが、ハッシュタグで全然第三者からみえるかどうか、、、

いや、今日一凹む。。。

**Comment by kobake** [comment]
Twitter、ときどき明文化されていない暗黙の仕様（？）があってよくわからんちんです。何かに引っかかってるんですかね～

**Comment by KENCHjp** [comment]
>Twitter、ときどき明文化されていない暗黙の仕様（？）があってよくわからんちんです。何かに引っかかってるんですかね～

URL付かないツイートをいっぱいしてるといいとか見つけましたが、活動記録のツイートなんてURL付きしか発生しませんしねぇ。。。

**Comment by KENCHjp** [comment]
あら、いまスマホからだと、
自分でつぶやいたURL付きツイートはハッシュタグで検索されるなぁ。
OSDNの活動ツイートは管理者アカウントのリツイートみたいになってるのでそれがなんか影響してるのかも。。。
OSDNさんに聞いてみるかな。

GitHubでは発生しないかもですね。

**Comment by KENCHjp** [comment]
OSDNさん原因じゃなかったっす。
メジャーすぎるハッシュタグつけると、その発言がスパム扱いされて、ついてるハッシュタグどれでも検索されなくなるようです。

私の場合「#カレンダー」ってハッシュタグ消すと付いてる他のハッシュタグで検索できるようになりました。

なので、試してませんが、もしかしたら#Windowsとかやばいかも。

**Comment by berryzplus** [comment]
#!/bin/sh

ソッコー試してみました。

メジャー過ぎて…という以前に!のところで切れてしまうみたいでした。

**Comment by kobake** [comment]
> メジャーすぎるハッシュタグつけると、その発言がスパム扱いされて、ついてるハッシュタグどれでも検索されなくなるようです。

なるほど

> もしかしたら#Windowsとかやばいかも。

試してみたけどダメっすね。自分の発言も検索結果には出ませんでした

**Comment by kobake** [comment]
と思ったけどちょっと待ったら（たぶん検索インデックス構築の都合）、出ましたｗ

<img width="582" alt="found" src="https://user-images.githubusercontent.com/2929454/43863869-f3376150-9b98-11e8-9471-55f1049d6ffc.png">

**Comment by KENCHjp** [comment]
#カレンダー やばすｗｗｗ

**Comment by KENCHjp** [comment]
とりあえず定常運用中につき閉じます。
