### ISSUE TITLE
OSDNフォーラムとGitHub Issuesの役割

### ISSUE THREAD

**Issue by KENCHjp** [sakura-editor/management-forum#26]
現在、ホームページの誘導が、以下のようになっている。

ページトップ
---
[▲HOME] [機能紹介] [ダウンロード] [GitHub Issues] [OSDNフォーラム]
---

ページ本文
---
* GitHub Issues … 要望・バグ報告等
* OSDNフォーラム … 匿名投稿可能な掲示板
---

となっている。
OSDNは一般利用ユーザーが使い方等を聞いたり、要望を出したりする用途（GitHubにアカウントが無い方)で、GitHubにアカウントがある方は、直接Issuesに書いてもらってもいいのかなって思うので、
ホームページの誘導の文言も、そのような誘導する文言にしてはどうかなと。

関連issues
https://github.com/sakura-editor/sakura/issues/326#issuecomment-412246776

**Comment by kobake** [comment]
Issue 立てありがとうございます。
内容がどのようなものであれ、基本的には GitHub Issues への投稿を推奨するようにしたいです。
OSDN は GitHub どうしても使えない人への救済措置的な場所という認識です。

GitHub の Issues の投稿数は増える分には構わないと考えています。
GitHub アカウントを作成して Issue 投稿できる時点である程度のリテラシは期待できるかと。

**Comment by KENCHjp** [comment]
>GitHub アカウントを作成して Issue 投稿できる時点である程度のリテラシは期待できるかと。

機能リクエストは、ある程度のリテラシは期待したいところですが、
テキストエディタは単なる物書きの人も使うものだったりするかと思うので、
単なる使い勝手や、こういうことできますか的なものを投稿しようとする場合、
GitHubの初期画面はやはり敷居が高いというか、どこに書いていいかわからず戸惑うのではないかなと言うのが私の感覚です。
GitHubの敷居の高さから本当はもっと機能リクエストが来ても良いところを取りこぼすのはもったいないかなと。

で、今のページトップの、 [OSDNフォーラム]を例えば、

［利用ユーザ向けフォーラム］

本文側を、例えば、

* 利用ユーザ向けフォーラム … OSDNフォーラムを利用した匿名投稿も可能な掲示板

みたいにしてはいかがかなと。
こちらだとユーザ同士でも助け合い可能じゃないかなと思っておりますがいかがでしょう。

**Comment by KENCHjp** [comment]
>基本的には GitHub Issues への投稿を推奨するようにしたいです。

こちらについては、異論はございません。

**Comment by KENCHjp** [comment]
>OSDN は GitHub どうしても使えない人への救済措置的な場所という認識です。

おそらくこの意思表示が今のトップページにないので迷子がでてくるのかも。

* GitHub Issues … 要望・バグ報告等基本的にはこちらを利用ください(GitHubユーザ登録が必要)
* 利用ユーザ向けフォーラム … OSDNフォーラムを利用した匿名投稿も可能な掲示板

こんな感じでどうでしょう。

**Comment by KENCHjp** [comment]
>どこに書いていいかわからず戸惑うのではないかなと言うのが私の感覚です。

こちら、ホームページからは直接SAKURAのIssueのページへのリンクでしたね。失礼しました。

**Comment by kobake** [comment]
> > OSDN は GitHub どうしても使えない人への救済措置的な場所という認識です。

> おそらくこの意思表示が今のトップページにないので迷子がでてくるのかも。

ですね。明示的に案内をしていなかったです。

自分が書くとしたらこんな感じです。

- GitHub Issues … 要望・バグ報告等はこちらからご連絡ください (GitHubユーザ登録が必要)
- OSDNフォーラム … GitHub投稿が難しい方はこちらをご利用ください (匿名投稿も可)

**Comment by KENCHjp** [comment]
> * GitHub Issues … 要望・バグ報告等はこちらからご連絡ください (GitHubユーザ登録が必要)
> * OSDNフォーラム … GitHub投稿が難しい方はこちらをご利用ください (匿名投稿も可)

いいとおもいます。

**Comment by KENCHjp** [comment]
結果反映されたのでとじます。

**Comment by ds14050** [comment]
現在 OSDN の「[Forum 一般話題（質疑・要望等） - SAKURA Editor - OSDN](https://osdn.net/projects/sakura-editor/forums/34071/)」で次のようなメッセージが表示されています。

>You are not logged in. This forum allows only logged in users to post. If you want to post in the forum, please log in.

「OSDNフォーラム … 要望・質問等GitHub投稿が難しい方はこちらをご利用ください (匿名投稿も可)」という案内なので設定ミスではないかと思います。経緯を見落としているでしょうか。

**Comment by berryzplus** [comment]
> 「OSDNフォーラム … 要望・質問等GitHub投稿が難しい方はこちらをご利用ください (匿名投稿も可)」という案内なので設定ミスではないかと思います。

本当ですね。
OSDNをログアウトするとページ左上隅になんか出ます :sob:

ぼくは [2ch](https://egg.5ch.net/test/read.cgi/software/1495286392/l50) や [wiki](http://sakura.qp.land.to/?RecentChanges) もたまに見てます。

優先度は issue << OSDN Forum << qp.land.to wiki << |超えられない壁| << 2ch のつもり。

> 経緯を見落としているでしょうか。

OSDNログイン必須にする話はありませんでしたよね？
デフォルト設定が変わったとかなのかなぁ・・・。

**Comment by KENCHjp** [comment]
あれ、なんかかえちゃったかな。見てみます。

**Comment by KENCHjp** [comment]
確かに匿名投稿がOffになってました。
すいません、以前、お知らせのみのRead Onlyのスレッド作ったときに障っちゃったのかもしれません。

**Comment by KENCHjp** [comment]
どうもプロジェクト履歴を遡るとどのフォーラムかは不明ですが「[プロジェクト設定] 公開情報変更」があるのが、2018-07-18にあるのでそこからかもしれません。
失礼しました。

**Comment by KENCHjp** [comment]
https://osdn.net/projects/sakura-editor/forums/34071/39855/

権限で、プロジェクトメンバーのみって設定してるのに、なぜか返信ボタンが表示されない。。。

**Comment by KENCHjp** [comment]
>権限で、プロジェクトメンバーのみって設定してるのに、なぜか返信ボタンが表示されない。。。

バグと言う事でした^^;

https://osdn.net/projects/support/ticket/38672

**Comment by berryzplus** [comment]
ぬはｗ

**Comment by KENCHjp** [comment]
そして速攻で修正されましたｗ

**Comment by KENCHjp** [comment]
てことで、また閉じさせていただきます。

@ds14050 さん、報告ありがとうございました。
m( _ . _ )m

**Comment by ds14050** [comment]
[Start New Thread] ボタンが確認できました。ありがとうございます。
