### ISSUE TITLE
DiscordにWebhookで連携できるそうなので設定してみました。

### ISSUE THREAD

**Issue by KENCHjp** [sakura-editor/management-forum#27]
DiscordにWebhookで連携できるそうなので設定してみました。
とりあえず、sakura-editorの活動全てを、#developmentに飛ばすように設定しました。
ためしなので、停止したほうがいいとか、飛ばす先のチャンネルや、活動を選んで飛ばすのもできます。

**Comment by KENCHjp** [comment]
参考にしたサイト

DiscordにWebhookで通知
https://zak1ck.info/discord%E3%81%ABwebhook%E3%81%A7%E9%80%9A%E7%9F%A5/

「Github形式のWebhook」にならって、/githubをwebhookアドレスに追加してます。

今の設定
![default](https://user-images.githubusercontent.com/39618965/44305224-96d4d380-a3ad-11e8-867b-3b712e0040cc.PNG)

設定するチャンネルによって飛ばす対象を変えられそうです。
![1](https://user-images.githubusercontent.com/39618965/44305226-99cfc400-a3ad-11e8-96c5-26aec339d0b8.PNG)
![2](https://user-images.githubusercontent.com/39618965/44305227-9b00f100-a3ad-11e8-870c-425d24d43eed.PNG)
![3](https://user-images.githubusercontent.com/39618965/44305229-9c321e00-a3ad-11e8-9026-25aa83b6486d.PNG)

**Comment by KENCHjp** [comment]
Content typeはjsonにしないとエラーになる模様です。

![default](https://user-images.githubusercontent.com/39618965/44305300-3e063a80-a3af-11e8-8821-6a8b551eb0d8.PNG)

**Comment by KENCHjp** [comment]
早速ですいません、飛ばす先のチャンネルを新たに作りました。

#github-active ってチャンネルを作りました。
最終的にはこのチャンネルなくなってもいいかなと思ってますが取り合えずためしにこちらに全件飛ばします。

**Comment by kobake** [comment]
良い感じです！設定お疲れ様です。しばらく様子見てみましょう～

**Comment by KENCHjp** [comment]
とりあえず定常運用中につき閉じます。
