### ISSUE TITLE
IFTTTで、TwitterのエゴサーチをDiscordに飛ばせそうなので設定してみる。

### ISSUE THREAD

**Issue by KENCHjp** [sakura-editor/management-forum#28]
参考にしたのは以下。
https://blog.k-san.info/discord-twitter-webhook
http://kengo700.hatenablog.com/entry/integration-twitter-slack

#サクラエディタ

を検索してDiscordのsakura-egosearchingチャンネルに飛ばします。

ひとまず、IFTTTとTwitterは私のアカウントで認証してます。

**Comment by KENCHjp** [comment]
![default](https://user-images.githubusercontent.com/39618965/44307336-93f0d780-a3db-11e8-8a3f-4bd5a85a6962.PNG)

トリガーにこんなlimitedがあるんですが、はてなににかかる制約なのか不明・・・

**Comment by KENCHjp** [comment]
チャンネル名を「sakura-egosearching」から、「egosearching」に変えました。
Facebookとかもエゴサできそうです。

**Comment by KENCHjp** [comment]
エゴサ文字列を、「#サクラエディタ」から「サクラエディタ」にしようか悩む、が、
「サクラエディタ」にすると「#サクラエディタ」よりも俄然ネガティブツイートが検索にヒットする(凹)

まそれがエゴサな訳ですが、、、

ひとまず「#サクラエディタ」のままにしておく。

**Comment by berryzplus** [comment]
勉強になりました。

IFTTT(イフト)って読むんですね。

そこかっ！ってツッコミどころなんですが名前を知るのは意外と大事。

**Comment by KENCHjp** [comment]
>そこかっ！ってツッコミどころなんですが名前を知るのは意外と大事。

かなり大事。
最近知ったのは、「Nginx」が「エンジンエックス」。。。

**Comment by KENCHjp** [comment]
結局、「エゴサ」なので開発メンバーだけ参照できる部屋にして「サクラエディタ」で検索するようにしてみたつもりですが、discordの設定が今一つ自身がない。。。

**Comment by KENCHjp** [comment]
検索文字列を、

サクラエディタ OR "sakura editor" OR sakura-editor OR sakuraeditor

にしてみる。
とはいえ「"sakura editor" OR sakura-editor OR sakuraeditor」でもほぼ日本語のツイートしかヒットせず。。。

**Comment by KENCHjp** [comment]
またものはためしで、私のツイッターアカウント（といってもOSDNの開発用）にOSDNの活動をツイートする設定を入れてみたのですが、IFTTT君がうまく拾ってくれないので、しばらく様子見てOSDNのTwitter連携解除します。(一応ツイートまでしてることは確認済なのですが、IFTTT君拾ってくれない。。。)

**Comment by KENCHjp** [comment]
>一応ツイートまでしてることは確認済なのですが、IFTTT君拾ってくれない。。。

拾ってくれたのを確認したので、しばらくそのままにします。
これでOSDNのフォーラムに書き込み合ってもDiscodeでチェックできる。。。人間怠けものになっていく気がしている・・・

**Comment by KENCHjp** [comment]
とりあえず定常運用中につき閉じます。
