### ISSUE TITLE
伏してお詫び申し上げます。

### ISSUE THREAD

**Issue by ds14050** [sakura-editor/management-forum#33]
報告が遅れて申し訳ありません。GitHub ID からメンバーの皆さんにメールを送る方法を探していました。30分以上経ちますがまだ動悸がおさまっていません。

何の報告か。誤って sakura-editor/sakura リポジトリを削除してしまいました。ひょっとして git リポジトリは復旧が可能かもしれませんが、Issues と Pull resuqests と Wiki などは GitHub から戻ってこないと警告を受けたものの中に含まれていた気がします。本当に、本当に申し訳ありません。

ただ、自分のアカウントのクローンリポジトリを削除したかっただけなのです……。

**Comment by beru** [comment]
permission 設定を管理者の方に見直してもらう必要がありますね。
googletest プロジェクトのSettings を確認してみたら Delete this repository ボタンが見えてびっくりしました。きっと sakura プロジェクトも同様だったんでしょうね。

自動で復旧出来たら良いですけど無理そうだったら Issue と PR をちゃちゃっと再登録すれば良いと思います。コメントとか消えたのは痛いですけど小さいプロジェクトだしなんとかなるでしょう…。

**Comment by beru** [comment]
> Issues と Pull resuqests と Wiki などは GitHub から戻ってこないと警告を受けたものの中に含まれていた気がします。

確認してみました。

https://help.github.com/articles/deleting-a-repository/

> Warning: These steps will permanently delete the repository, wiki, issues, and comments. This action cannot be undone.

という事なので無理そうですね。[Wiki](https://help.github.com/articles/adding-and-editing-wiki-pages-locally/) はリポジトリをどなたかが持っていれば復旧出来ると思います。

**Comment by ds14050** [comment]
Contact Human から GitHub の方にお願いメールを出してみました。

**Comment by beru** [comment]
ChromeのCacheから復旧できるものは復旧してみます。

**Comment by beru** [comment]
repositoryは @m-tmatma さんのとこから import して復旧出来たようです。色んなブランチもくっついてきましたが後で管理者の方に消してもらいましょう。

**Comment by beru** [comment]
Chrome の Cacheを [ChromeCacheView](https://www.nirsoft.net/utils/chrome_cache_view.html) で確認しましたがあんまり残ってませんでした。

https://stackoverflow.com/questions/9247961/recover-a-deleted-repository-github-issues
にはサポートにお願いして復旧してもらった事例とかが載ってました。大分昔の話ですが。。

**Comment by beru** [comment]
Issue と PR のタイトルを Discord の github-active チャンネルのログから目grepしてコピペしました。
bot作って Discord APIでやった方が良いかもですが…。

もし運悪く Issues と Pull Requests を自動復旧出来ない場合は、（番号合わせて？）再登録しなおすのかそれとも過去は捨てて新規にやり直すのかとか決めて進めていきましょう。

# Issues

```
#6: ビルド要件の精査と記述
#12: cmake 対応
closed #28: pre-build, post-build の Power Shell 対応
#30: 開発コアメンバー募集
#35: sakura-developers チーム情報がチーム外からも見えるようにする
closed #37: Appveyor で強制リビルドする方法
closed #39 MakefileMake  を #18 の変更に対応させる
closed #66 bregonig.dll に perl_license.txt と perl_license_jp.txt を同梱する
#75: grep/grep 置換で除外ファイル、除外フォルダを指定できるようにする
#78: sakura editor の自動更新の仕組みについて検討する
#107: [保留中] windows7 の AeroSnapに対応させる
closed #153: バージョン番号の一番末尾の番号にビルド番号を入れる
closed #160: CNativeT に auto_sprintf の機能を持たせたい
#209: インストーラの UI を英語対応にできないか検討する
#224: ヘッダのプロトタイプ宣言で変数名が省略されて型名しかないものに明示的に変数名を指定する
#309: appveyor で MingW ビルドする
#326: マクロ関数の選択開始桁と選択終了桁で取得できる数値が桁数でない
#344: zipArtifacts.bat  でリポジトリに登録されている bregonig.dll が成果物にコピーされる
#348: zip ファイルの圧縮、解凍方法について検討する
closed #349: MinGW向けメイクファイルでサクラエディタをビルドできるようにする
#356 独自例外を定義して使うようにしたい
closed #357: HTML Help Workshop (Visual Studio 2017 のインストール)に関して
#358: ビルドで生成されるファイルをクリーンで削除するようにしたい
#368 cppcheck の結果を見やすく整形する
#372 run-cppcheck.bat をリファクタリングする
closed #373 run-cppcheck.bat で cppcheck に -j オプションを渡して複数のソースを同時にチェックする
closed #379 デフォルト値変更リスケスト「ファイル排他をしない」に変更
closed #380 HTML Help 中のリンクを GitHub のものに変える
#382 new/deleteのオーバーロードに対するGCC警告に対応する
#384 HTML ヘルプ中のバージョン番号に関して考える
#385 GREP置換ダイアログを出すマクロが実装されていない。
closed #388 installer\externals\bregonig\bron412.zip がビルド要件になっている件について
closed #389 非推奨テンプレートstd::auto_ptrを一括置換したい
#394 セキュアでない関数をセキュアな関数に置き換える
#395 Program Files や Program Files (x86) のパスを決め打ちせずに環境変数を参照する
#397 ダイアログの表示位置が表示するたびにずれていく
closed #398 特定のファイルで描画が遅くなる。
closed #400 sakura_core/util/other_util.h にある auto_array_ptr も廃止して、std::unique_ptr で置き換える
#401 ファイルパス長が MAX_PATH を超えるファイルに関して検討する
closed #406 アウトライン解析ウィンドウのタイトルバーをマウスで動かすと表示されるドッキング位置の表示が高DPI環境でおかしい
#410 エクスプローラの右クリックメニューに、『サクラエディタで Grep』を追加する
#412 各種ビルド用のバッチファイルで 各種ツールのパス検索方法の改善を検討する
#413 プリプロセッサの # とキーワードとの間にスペースがある場合に強調表示するか検討する
#414 タスクトレイから GREP置換ダイアログを出す機能が実装されていない
#417: インストーラの英語対応で見つかった課題について検討
#419: Grepのコマンドラインオプションを分かりやすくしたい
#420 エディタの各ドキュメントのタブ部分の右クリックメニューでエクスプローラを開く機能を検討する
#424 Grep でバイナリファイルを除外するオプションを追加できないか検討する
#425 サクラエディタをタスクバーにピン止めしたい
#426 build.md  の MingW のコンパイルに関する説明を更新する
#427 appveyor のビルドで削れるものがないか検討する
#429 Windows10対応を何をもって対応と言うか。
#430 x64対応を何をもって対応と言うか。
#431 次期リリース機能選定
#432 travis ci で cppcheck を実行出来ないか調査する
closed #434 googletest から Catch2 への乗り換えを検討
closed #437 メールアドレスクリック時の動作
#438 タイプ別設定の色指定でURLにチェックを入れているとメールアドレスも色付けがされる
closed #439 タイプ別設定のカラーで強調キーワードの共通設定を押すと表示されるダイアログ表示でボタンが切れている
#442 Windows10の仮想デスクトップの挙動が怪しい
#445 スクロール操作時の処理負荷について
#446 Azure Pipelines を調査する
closed #447 バージョンダイアログの "Share Ver" に関して
#448 exuberant ctags をインストーラに同梱したい
#450 exuberant ctags を Universal ctags  に差し替えるか検討する
#457 共通設定のタブを使いやすくしたい
```

# Pull Requests

```
#46: [WIP] cmake 対応の実験
#297: cppcheck の appveyor ビルドに対応
#304: btool 配下のソースコードを UTF-8 (BOM付き) に変換
#306: Makefile調整：入力ファイルUTF-8指定、GitHash出力
closed #312: メモリプールを使ってファイル読み込み時のメモリ確保を高速化
#351 MinGWでサクラエディタをビルドできるようにメイクファイルを更新する
closed #352 btoolフォルダを削除する
#353 markdown で成果物のダウンロード方法が実態にあっていないのを修正
#354 警告を解析して excel ファイルに出力処理で同一の警告を一つのシートにまとめて出力する
#355 Appveyor 関連の環境変数をバッチファイルの形で保存する
#359 インストーラの UI を英語対応にする
closed #360 githash.bat のエラー耐性を改善する
#361 funccode.bat のエラー耐性を上げる
#362 ビルド関連のバッチファイルの引数のチェックを実装
closed #363 MINGW_HAS_SECURE_APIが無効か判定する式の修正
closed #364 cppcheck の出力 xml ファイルに platform 名や configuration 名を追加
#365 ビルドの前提条件を整理して StdAfx.h に含めたい
closed #366: HTML Help Workshop がVS2017で導入される条件
closed #367 cppcheck で "Too many #ifdef configurations - cppcheck only checks 12 of 31 configurations. Use --force to check all configurations" の警告を修正
closed #369: sakura_lang_en_US.dll の MinGW 向け Makefile を更新する
closed #370 PR #355 の対応漏れを修正
closed #371 [WIP] MinGW向けMakefileからbtoolフォルダへの参照を取り除く
closed #374 githash.batも exit /b 0 にする
closed #375 run-cppcheck.bat をリファクタリングする
closed #376 cppcheck で -j オプションを指定して同時に複数のチェックを行う
closed #377 cppcheck の標準出力をリダイレクトしてファイルに落とす
#378 [WIP] cmake 対応の実験 (part2) 更新版
closed #381 new/deleteのオーバーロードがGCCに怒られる対応
closed #383 HTML Help 中のリンクを GitHub のものに変える
#386 deleteのオーバーロードがGCCに怒られる対応
closed #387 #357 build.mdの「HTML ヘルプのビルドに必要なもの」　レビュー結果反映
closed #390 bron412.zip の解凍が必要ないときは bron412.zip の解凍をスキップする
closed #391 ビルド時に 7zip が利用可能でない場合 7zip をインストールするように促すメッセージ出力する
closed #392 ソースコード中のオンラインヘルプのアドレス更新
closed #393 単体テストのプロジェクトの言語を指定する (プロジェクト生成が 11秒→10秒程に短縮)
#396 非推奨テンプレートstd::auto_ptrを一括置換する
closed #399 Program Files や Program Files (x86) のパスを決め打ちせずに環境変数を参照する
closed #402: インストーラに perl_license.txt と perl_license_jp.txt を同梱する
#403: grep/grep 置換で除外ファイル、除外フォルダを指定できるようにする
closed #404 auto_array_ptr を廃止して std::unique_ptr に置き換え
closed #405 コメントの修正
closed #407 MinGW Makefileをデバッグ/リリース両対応にする
closed #408 CSearchKeywordManager のコメントの間違いを修正
closed #409 ファイルを開く、で _MAX_PATH (260) より長いパスのファイルの場合はエラーメッセージを出して処理を中断
closed #415 タスクトレイのメニュー項目のデバッグ方法 に関するドキュメントを追加
closed #416 push_back を emplace_back に置き換え
closed #418 CGrepAgent::SetGrepResult 出力形式がノーマルの場合の処理の高速化
closed #421: メールアドレスの色替え判定を高速化すると同時にRFCに準拠させる
closed #422 単体テストのプロジェクト設定で sakura editor 本体のソースコードのインクルードディレクトリの指定を追加する
closed #423 string_ex2.h での CNativeA/CNativeW の先行宣言漏れを修正
closed #428 exeに高DPI対応のmanifestが埋め込まれるようにする
closed #433 ユニットテストフレームワーク を googletest から Catch2 へ変更
closed #435 単体テスト向けの CMakeLists.txt で Visual Studio のスタートアッププロジェクトの設定
closed #436 README にカンバンリンクを追加
closed #440 Pull Request を簡単にローカルに取得するためのバッチファイルを追加 (take2)
closed #441 ctestを有効にする
closed #443 タイプ別設定のカラーで強調キーワードの共通設定を押すと表示されるダイアログの高さ調整、DPIスケーリング
closed #444 インストーラーのデバッグ方法を追記。
closed #449 バージョンダイアログの "Share Ver" 表記を削除する
closed #451 exuberant ctags 日本語対応版をインストーラに組み込む
#452 ステータスバーのテキスト設定、既に同じ値が設定されている場合は再設定しないようにする
#453 SetScrollInfo の呼び出しを抑制
#454 Universal ctags を組み込む
closed #455 bregonig のライセンスファイルをライセンス用のサブフォルダに配置する
#456 ツールバーの状態更新を必要な場合にのみ行うように変更
#458 ヘルプの説明を exuberant ctags → Universal ctags に変更する
#459 [WIP] 共通設定ダイアログの仕様まとめ
#460 IME編集エリアの位置を変更を行う ImmSetCompositionWindow の呼び出しは IMEが開いている時だけに限定
#461 ヘルプの説明を exuberant ctags → Universal ctags に変更する
#462 README.md にダウンロード数のバッチを追加する
```

**Comment by KENCHjp** [comment]
目覚めました、見慣れないメール来てたので見渡したらあら一大事(笑)

@ds14050 さんのお願いメール待ちですが、望み薄そうですかね。
返事をまってから、消えたものはしょうがなさそうなので、 @kobake さん同意の元作り直しですかね？

権限こういうことを想定して絞ったほうがフェールセーフ的に良さそうですね。

とりあえずリポジトリは復旧できたみたいですのでよしとして。

PR は各自自分のリポジトリから投げなおせるものは投げなおしかな（たしかマージしてないのが１１本ぐらいだったかと）

Wikiは整理しようって話してたので、新たに入れ直ししかなさそうっすよね。

あとは、Issueですねぇ。 #github-active頼りに、入れるべくを入れ直しっすかね。

**Comment by KENCHjp** [comment]
カンバンは復旧できなければ、私作り直します！
その前にIssueが戻らないと話にならないですが、リポジトリが何とか復旧出来てるのでなんとかなるっしょ。

**Comment by KENCHjp** [comment]
@beru さん書いた事例のように、たぶんサポートが何とかしてくれれば復旧は簡単そうですね。
私からもメールだしておきますかね（英語苦手ですが。。。）

**Comment by KENCHjp** [comment]
一応、ちょっとくどいかとおもいましたが、
https://github.com/contact と、support@github.com にもメール出してみました。

**Comment by m-tmatma** [comment]
github かなんとかしてくれるかわかるまで
リポジトリ触らないほうがいいですね。

**Comment by m-tmatma** [comment]
https://sakura-editor.github.io/
で状況を公開した方がいいですね。

**Comment by m-tmatma** [comment]
GitHubリポジトリが突然消えたときにやるべきこと
http://tech.grooves.com/entry/2017/01/18/111900

**Comment by KENCHjp** [comment]
>リポジトリ触らないほうがいいですね。

ですね。
いまあるsakura-editor/sakura がじゃまになるかもしれませんが、これ以上触ると二次災害おこしそうなのでひとまず静観で。

出社しちゃったのでスマホ操作になりますが、なんかあればここに書き込みします。

一応サポート連絡すれば復旧してくれそうですね。
私の拙いルー英語がかなり不安なのでどなたか状況メール打ってくれると心強いです。

**Comment by KENCHjp** [comment]
あ、@ds14050 さん消えないでくださいね。
オペミスじゃなくても、@m-tmatma の事例でなにかのはずみでリポジトリ消える事態がありそうなので、これを実践訓練で教訓にしましょう！

**Comment by KENCHjp** [comment]
返事来た。
同じ名前のリポジトリもてないから、名前変更か削除しろと来ました。リネームこころみます。

**Comment by KENCHjp** [comment]
リポジトリリネームして、返事してみました。

**Comment by kobake** [comment]
皆さまご対応ありがとうございます。

ミスはしゃあないですし、リポジトリは一般ユーザ向けというよりは開発者向けなのでまぁ影響は大きくないと考えて良いと思います (リリースバイナリを正式配布しだした後は慎重にすべきですが)。一旦サポに任せましょう。

ちなみに全員にAdmin付けてたのは僕の怠慢です、すみません。折を見て権限は見直しますが、しばらくはオペミスも織り込み済みで考えるくらいで良いと楽観的に考えてます。Git自体が性善説で成り立ってるシステムですし。あまりGHサポートの方の手を煩わせないようには注意したいですが。

**Comment by m-tmatma** [comment]
すばらしい。復旧できそうな感じですね。

**Comment by kobake** [comment]
ちなみに連絡手段はこのフォーラム用リポジトリに加えてDiscordがあるのと、あとはgit logコマンドで実はコミッタの方々のメアド見えますw
状況に合わせて何かしら連絡とれればOKかと。今回はこの場がベストだったと思います。

**Comment by m-tmatma** [comment]
> オペミスじゃなくても、@m-tmatma の事例でなにかのはずみでリポジトリ消える事態がありそうなので、これを実践訓練で教訓にしましょう！

今回の件に関して、どういう経緯で問題が起きたか、
問題が起きたあと各自何をしたかをローカルでもいいので記録に残しておいてほしいです。
あとで再発防止策の検討や検証に使えるようにしときたいです。

**Comment by KENCHjp** [comment]
復旧してますね。お礼メールしておきます。

フォームで入力するよりも、support@github.com へメールするのがかくじつっぽいですね。

**Comment by berryzplus** [comment]
とりあえず一点だけ。

どんまい。


元に戻りそうで良かったです。お礼言っとかなきゃですね。

**Comment by beru** [comment]
Issues や Pull Requests の Labels は復旧対象外みたいですね。
コメント履歴には残ってるので付け直しは簡単そうです。

**Comment by m-tmatma** [comment]
Y

**Comment by m-tmatma** [comment]
各自、自分の関心のある issue  やPR に問題ないか確認お願いします

**Comment by KENCHjp** [comment]
なるほど、付けたラベルはきえてるっぽいですね。

**Comment by beru** [comment]
ラベル候補が無いので付けられません。ラベル候補のエディットが出来ないような。。

**Comment by beru** [comment]
sakura repository  の権限ですが、他の人が作成した Issue や Pull Request の Close が 行えないようです。
もし問題無ければ Members にも付与お願いします。

**Comment by KENCHjp** [comment]
ラベル候補？
一応、IssueとかPRの中に何がついてたかの痕跡があるので、付けられそうです。
気づいたものからつけられそうです。
権限周りが見直し要かな。。。

**Comment by beru** [comment]
Pull Request で Approve したのに Merging is blocked と表示されています。

**Comment by beru** [comment]
> ラベル候補？

権限の問題だと思いますが、Assignees, Labels, Projects 等の設定が行えません。
Gear のアイコンが表示されていません。

**Comment by KENCHjp** [comment]
@beru  さん権限周りの設定明るいです？
私やると二次災害起こしそうで(笑)
不安であれば、有識者に頼りましょう。今日は慎重に。

**Comment by beru** [comment]
明るくないですが下記のサイト見ればばっちし分かるので問題無いですよ。
管理者の方頑張ってください。応援しています。
https://help.github.com/

**Comment by kobake** [comment]
sakura へのチーム権限外れていたので権限付け直しました。

今の時点では全員Adminになってます。復旧作業のため、権限はあったほうが良いでしょう。
権限の絞り込みは復旧完了後にでも。

**Comment by beru** [comment]
権限については下記のページ以下を辿ると良いと思います。
https://help.github.com/articles/access-permissions-on-github/

> 今の時点では全員Adminになってます。復旧作業のため、権限はあったほうが良いでしょう。

ひー危ない

**Comment by ds14050** [comment]
おはようございます。このたびは多大なご迷惑と、そして不安をみなさまに与えてしまいました。あらためて、申し訳ありませんでした。

>フォームで入力するよりも、support@github.com へメールするのがかくじつっぽいですね。

そのようです。こちらは自動応答メール以外の返信が来ていません。

**追記** 送信から10時間後の日本時間10:40には、復旧を進めるとの返信が来たので、「今はもう見えるよ、ありがとう」と返信しておきました。

>カンバンは復旧できなければ、私作り直します！

カンバン、見あたりませんね。見え方が変わるだけで受け止め方が大きく変わることに驚いていました。メンバーのリアルタイム(それに近い)の注目を集めて、特定の目的に向かわせるのが用途だと思いますが、まさしく百聞は一見に如かずでした。

>今回の件に関して、どういう経緯で問題が起きたか、

1. 自分のアカウントのホームページをうろうろしてリポジトリを削除する方法を探していたが、「Settings」タブがそれだと見つけられなかった。
2. Web 検索をしてそれを知る。
3. ブラウザで **元のタブに戻って** Settings タブを表示すると確かに「Delete this repository」というボタンがある。
4. 実行前には「**元には戻せないという警告**」が表示され、「**確認のために削除するリポジトリの名前を入力**」する必要があるが、個人のクローンリポジトリだと思っていたので、警告は歯止めにはならず、リポジトリの名前はオリジナルと同じものだった。

3 で、自分の見ているリポジトリを勘違いしたことが原因です。

クローンリポジトリなので、リポジトリのファイル構成や最新コミットの概要など、ページの大部分を占める要素が同じになります。確実に見分けられる方法が **GitHub メニュー直下の sakura-editor/sakura というリンク**。見分ける手がかりになるのが **Unwatch/Star/Fork の数、Issues/Pull requests の数** ではないでしょうか。

今となっては、git リポジトリで自分がどのブランチにいるのか、と同じくらいの注意を払うべき要注意ポイントだったと感じます。

@beru さん、@m-tmatma さん、@KENCHjp さん、@kobake さん、@berryzplus さん、昨夜からの行動と反応に感謝するばかりです。

**Comment by KENCHjp** [comment]
カンバンありますー！
まちがえてました。カンバンはリポジトリじゃなくて、全体で作ってました。失礼しましたー。

**Comment by KENCHjp** [comment]
リポジトリ消すときは、名前だけじゃなくて、ユーザ名も込みで入力するといいと、
どこかのページで見たので、私も今後はそれ実践しようと思います。

**Comment by k-takata** [comment]
> リポジトリ消すときは、名前だけじゃなくて、ユーザ名も込みで入力するといいと、

ユーザー名なしでも消せるんでしたっけ？
確認画面はユーザー名込みのリポジトリ名が表示されますが。

**Comment by KENCHjp** [comment]
>ユーザー名なしでも消せるんでしたっけ？

お、じつは常にユーザ名つきでいれてたかも。
なんかそんなページみかけたきがしたので、そのままかいてしまいました。

**Comment by k-takata** [comment]
もし、本当にユーザー名なしでも消せるのだったら、必須にするようにGitHubにお願いした方がよさそう。

**Comment by KENCHjp** [comment]
ここで紹介されてたページの、

http://tech.grooves.com/entry/2017/01/18/111900

>1. 削除時の確認
>今回の件で初めて知ったのですが、リポジトリを削除するときの確認画面でリポジトリ名だけでなく ユーザー名 も入力することが可能です。

こんな記述があったので、ユーザ名無しでも行けるんだぁって思っちゃいました。
もしかしてユーザ名無し＝自分のリポジトリなのかもしれませんが。

**Comment by kobake** [comment]
今回の件、自分はあんまり深刻に受け止めてないです。
むしろ今のうちに事故れるだけ事故っておきましょうくらいの感覚です。

危険性云々よりもスピーディさのほうを今は優先したいです。
Admin権限絶対に持ちたくないでござる、って人は進言してください。それ用に別チーム作ります。

**Comment by m-tmatma** [comment]
そもそもなんのために削除しようとしたのですか？

**Comment by KENCHjp** [comment]
自分のforkを削除しているつもりで、sakura-edhitorを消してたってことなのかなと。

> ただ、自分のアカウントのクローンリポジトリを削除したかっただけなのです……。

私も、いまだにfork消すのは緊張しますwww

**Comment by k-takata** [comment]
ごめんなさい、勝手にタイトル変えちゃいました。
通知のたびに (消えたい) などと表示されると、見ているこっちまで鬱になってくるので。

**Comment by m-tmatma** [comment]
そうではなくて fork を削除しようとした理由です

**Comment by KENCHjp** [comment]
ああ、そっちですか、失礼しました。

**Comment by kobake** [comment]
ちなみに自分もリポ削除はよくやります。設定周り(webhook周りとか)やりなおしたいときとか。sakuraでもAppVeyor設定見直すために何度かfork消してますね。誰にでも起こり得た事故だと思ってます。

**Comment by ds14050** [comment]
>ユーザー名なしでも消せるんでしたっけ？
>確認画面はユーザー名込みのリポジトリ名が表示されますが。

はい。`sakura` とだけ入力して Enter を押したら消えていました。

実際には消えているはずの自アカウントの sakura リポジトリが消えておらず、再度同じ操作をし、今度は消えているのを確認してから、本家サクラエディタのリポジトリが消えていることに気がつき、最初の操作で何を消したのかを知った次第です。ブラウザの閲覧履歴を確認しても、やはり最初の操作は `https://github.com/sakura-editor/sakura/settings` にアクセスして行っていました。

>そうではなくて fork を削除しようとした理由

現在は何かをしようとする度に `git clone` をしては削除しています。回線負荷がアレですが。まだ `git pull` や `git fetch` のようなコマンドを覚えていないのです。

今回の件は特に、ローカルで `git clone` したものを GitHub の空リポジトリに `git push` したものでは本家に Pull Request を飛ばせなかったので、フォークするところから作り直そうとしていて起こった事故でした。

**Comment by m-tmatma** [comment]
以下登録しました。

- #34 GitHub リポジトリのバックアップを検討する
- #35 sakura リポジトリのアクセス権に関して検討する
- #36 誤削除を防ぐような機能を検討してもらえるように GitHub に要望を出す

**Comment by ds14050** [comment]
>Admin権限絶対に持ちたくないでござる、って人は進言してください。それ用に別チーム作ります。

身に染みた同じミスは繰り返さないつもりですが、２人目の方がいらっしゃれば、チームの作成とそこへの登録をお願いしておきます。管理の面倒がそれほどでなければ１人チームでも構いません。UAC がない Windows XP の頃から一般ユーザーで個人 PC を操作していました。

**Comment by KENCHjp** [comment]
実は私も、この前まで、本家リポジトリのコミットを、自分のforkに反映できず、最新から毎度forkしては、PR後に自分のforkをドキドキしながら消してましたｗｗｗ。
いまだ、リベースがよくわかってませんです(笑)

**Comment by m-tmatma** [comment]
> > Admin権限絶対に持ちたくないでござる、って人は進言してください。それ用に別チーム作ります。
> 
> 身に染みた同じミスは繰り返さないつもりですが、２人目の方がいらっしゃれば、チームの作成とそこへの登録をお願いしておきます。管理の面倒がそれほどでなければ１人チームでも構いません。UAC がない Windows XP の頃から一般ユーザーで個人 PC を操作していました。

https://github.com/orgs/sakura-editor/teams/sakura-developers/members
にアクセスすると "Leave Team" というボタンがあります。

自分でチームから抜けられるみたいので、sakura-admin みたいなチームを作って
sakura-developers と同じメンバーを登録しておいて自発的に抜けられるように
してはいかがですか?

**Comment by ds14050** [comment]
あ、自分でチーム作れますね。作ってから sakura-developers を抜ければいいんだ。そうすると作るのは sakura-非admin を意味するチームになると思いますが。

**Comment by ds14050** [comment]
チームの親子関係について。

* 子のパーミッションは親から引き継ぐ
* 親への＠メンションは子へも飛ぶ

頂点が下の逆ピラミッド型のチーム階層が自然なのだろうか。

* 親 - 非Admin - sakura-developers
* 子 - Admin - sakura-admin (sakura-developers としても振る舞う)

**Comment by m-tmatma** [comment]
> 現在は何かをしようとする度に `git clone` をしては削除しています。回線負荷がアレですが。まだ `git pull` や `git fetch` のようなコマンドを覚えていないのです。

例えば私の fork を取得して最新にしたい場合以下のようなコマンドを実行します。
`m-tmatma` の部分は自分のアカウントに読み替えます。

```
git clone https://github.com/m-tmatma/sakura.git
cd sakura
git remote add upstream https://github.com/sakura-editor/sakura.git
git pull upstream  master
git pull origin    master
git push origin    master
```

1. clone します。
2. ディレクトリ移動します。
3. オリジナルのリポジトリを `upstream` という名前でアクセスできるようにします。
4. `upstream` のリポジトリの `master` を取得しながら ローカルリポジトリの `master` にマージします
5. fork のリポジトリの `master` を取得しながら ローカルリポジトリの `master` にマージします (通常は不要です。やっても害はないです)
6. fork のリポジトリの `master` にマージした結果を push します。

→ これで fork リポジトリが オリジナルのリポジトリに追従できます。

**Comment by m-tmatma** [comment]
あるいは 自分の fork リポジトリで  sakura-editor/sakura → 自分のアカウント/sakura に対してPR を
なげて自分でマージしても最新に追従できます。

**Comment by m-tmatma** [comment]
アクセス権に関しては #35 を作ったので続きはそちらで。

**Comment by m-tmatma** [comment]
#37 に Git/GitHub に関する質問部屋という issue を作りました。

**Comment by ds14050** [comment]
実は m-tmatma さんの get-PR.bat のようなツールのソースを参考にしたりもしています。

git が暗黙にうまくやってくれるところが、実は、未知のサブコマンドに対する怖さの源だったりします。

たとえば、
```
5| git pull origin master
```
が fork元の master を取ってくることに関して。`git clone` が暗黙の `git remote add origin fork元` を実行しているのかなとか、origin の master ブランチを指定する引数がおそらく省略されているのだろうなとか、そういうあたりです。

知って、省略するのはいいのですが、知らないまま、うまくレールに乗せられて勝手に運ばれるのはダメなのです。

ごちゃごちゃ言ってないで使って慣れろってことなんですが、まだ慣れません。

**Comment by m-tmatma** [comment]
> ごちゃごちゃ言ってないで使って慣れろってことなんですが、まだ慣れません。

プログラミング、数学、物理、英語、たぶんどれも実際に使って、間違って覚えていくのだと思います。
git も同じだと思います。間違っても大丈夫なテスト用のリポジトリ作っていっぱい間違えましょう。

**Comment by berryzplus** [comment]
実はちょっと前に、誤操作で sakura-editor/sakura に変なブランチ作ったことあるんですよ。

すぐに気付いてあわててブランチ消したんですけど、
その時に「あ、勝手にブランチ作れるんだ」と気付きました。
よくよく考えると、そのとき作ったブランチ普通に消せてますね。（へぇ～消せるんだ・・・ :cry:

知らないって怖い。

今回のことはちょっとびっくりしました。
びっくりしたけど・・・結局びっくりしただけで終わったと思ってます。
意外と「GitHub あるある」なんですね。GitHub怖ぇ・・・

軽く考えてはいけないのかも知れませんが、重く受け止め過ぎないように、
これからも @ds14050 さんの鋭い視点の突っ込みを期待しております。

**Comment by beru** [comment]
Permission 設定ちゃんとしないで運用しているところが怖いです。ひぃぃー

**Comment by kobake** [comment]
いやいや怖がりすぎです。

理想論を抱くのは良いんけど、もともと GitHub 移行前の SourceForge 時代にはもっともっと雑な運用してきた経緯があります。それをいきなりモダンな理想運用にもっていくこと自体がサクラエディタの文化に合っていません。

いきなりではなく徐々にグラデーション的に安全運用に移行していくのがこのプロダクトチームの空気に合っていると考え、「あえて」雑な運用を自分は選択しています。

しっかり説明していなかった自分が悪いですが、ここで名言しておきます。
**今の雑運用は「あえて」そうしています。**

「曖昧運用」→「カッチリ運用」にいきなり持っていくよりは
「曖昧運用」→「やや雑運用」→「カッチリ運用」というようにワンクッションかましたほうが、このプロダクトの空気に合っていると思っています。いちいち説明するのは野暮と考え説明していませんでしたが、このような意図があることをご理解お願いします。

SourceFore 時代に比べて割とメンバーが総入れ替えに近い形で変わったこともあり
カッチリ運用にしたがるメンバーが多い（ように見える）ことも理解しています。
ただ、しばらくはやや雑運用でやらせてください。

GitHub 移行によって、これまでの空気が一変していきなり（もう少し時間をかけてならまだ良いのですが、ちょっとここのところのカッチリ移行速度が早すぎるように感じています） **「仕事みたいなカッチリ運用」になりつつあることにやや「引いてしまっている」方々が少なからずいるのではないか** とも自分は懸念しています。

仕事じゃないのであんまりカッチリやらなくて良いです。特に新規参入者のハードルを下げることも視野に入れてみてください。それは安全面よりも重要であると自分は考えています。少なくとも今のフェーズでは。

カッチリ運用のメリット＆デメリット両方について考えを巡らせてみてください。

**Comment by kobake** [comment]
要するに何が言いたいかというと、カッチリ運用すべきかどうかは **プロダクト次第** ということです。
今の時点のサクラエディタはまだそこまで気を遣うフェーズではないと自分は判断しています。

ただ、ちょうど今回事故がありましたので、権限周りを見直す良い機会にはなるでしょう。
管理者がどうこう判断することに加えて、メンバー全員がそれについて考えを巡らせるキッカケになったという意味で。

**Comment by beru** [comment]
もう復旧して平常運転になったと思うので Close します。

**Comment by KENCHjp** [comment]
色々と勉強になりました！
いい方に転がして行きましょう！
