### ISSUE TITLE
GitHub リポジトリのバックアップを検討する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/management-forum#34]
GitHub リポジトリのバックアップを検討する
https://github.com/josegonzalez/python-github-backup

`--issues` `--milestones` `--pulls` のようなオプションがあるので、たぶん issue や PR もバックアップしてくれると思う。

**Comment by m-tmatma** [comment]
`--all` というオプションがあるので実際には、これを使ったらいいと思う。

**Comment by m-tmatma** [comment]
`--wikis` というオプションもありますね。

**Comment by KENCHjp** [comment]
そのバックアップは、ここの別リポジトリになるって感じですかね？

引数あるってことはCLIですよね。
どっかで実行してバックアップをアーカイブするかんじですよね。
リストアどうするんだろう。。。

**Comment by m-tmatma** [comment]
わからないです。まだ全然調べてないです。

http://tech.grooves.com/entry/2017/01/18/111900
 によると
https://backhub.co/ 
というサービスもあるようですが、有料みたいです。

**Comment by KENCHjp** [comment]
>わからないです。まだ全然調べてないです。

了解っす！
使えそうなら使いましょう！

**Comment by m-tmatma** [comment]
誤削除を防ぐ対策が、運用ルール上でも、
github  側でも行われたので、閉じます。
