### ISSUE TITLE
sakura リポジトリのアクセス権に関して検討する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/management-forum#35]
sakura リポジトリのアクセス権に関して検討する

**Comment by m-tmatma** [comment]
@k-takata
https://github.com/sakura-editor/management-forum/issues/33#issuecomment-422239304

> もし、本当にユーザー名なしでも消せるのだったら、必須にするようにGitHubにお願いした方がよさそう。

**Comment by beru** [comment]
Member は `Delete this repository` が出来ないように早急に設定してもらいたいです。
@KENCHjp @kobake

**Comment by kobake** [comment]
意図は伝わりました。

必ずしも早急である必要性は個人的には同意しかねますが、一意見として受け入れます。近いうちに対応方針考えて実施しようと思います。

**Comment by kobake** [comment]
あのね、あえて名言させていただきます。
これは @beru さんに限ったことではないのですが、OSSメンバーに対してタスク消化を急かすようなことはやめてください。 **これは仕事ではありません。**

仕事っぽさを求めるのであれば @beru さんにオーナー権限を譲渡することも考えます。必要であればご進言ください。

あくまでも必要を感じた人自身がその人自信の手で（権限などの事情で可能であれば）その人がやっちゃう、というのがOSSの文化です。人に押し付けるのはNGです。自分が10年間近くサクラエディタに関わらなくなったのも以前に同様のケースがあったからというのが実際の理由です。

ここに自分の考えを書きました。
https://github.com/sakura-editor/management-forum/issues/33#issuecomment-422532594

**Comment by kobake** [comment]
@sakura-editor/sakura-developers は sakura リポジトリに対して Write 権限を持たせるのみにしました。

また、新しく @sakura-editor/sakura-admins チームを新設しました。
このチームは sakura リポジトリに対して Admin 権限を持たせることにしました。

たまたま今日は早起きしたのでこの作業やりましたが、 **「早急に」と言われて睡眠時間削るほど自分は酔狂ではありません。** そのあたりご理解お願いします。以前はそういうこともやっていましたがさすがに疲れました。

@sakura-editor/sakura-admins にはあえて @beru さんも追加しましたが嫌なら抜けてください。
@sakura-editor/sakura-developers  のメンバーは現状を維持しています。

**Comment by beru** [comment]
@kobake 設定ありがとうございました。

OSS活動は義務ではないのはおっしゃる通りです。負担の強制に関して意識が足りてませんでした。ごめんなさい。

あわてて急かしたのは Member が `Delete this repository` 操作が出来てしまう状態に放置していると、いつそれが発生しても別に不思議な事ではないと捉えているからです。

仮に自分が Sakura Editor organization のリポジトリ消しまくってついでに逃走したら、「また消えたのかよウッキー」という状態になるでしょう。誰が操作したかの記録とかは残ってて admin は見れると思うので後で頃されると思うのでいたずらはしませんが。

**Comment by m-tmatma** [comment]
設定終わったみたいなので閉じます。

**Comment by berryzplus** [comment]
後出し対応になって申し訳ないです。
maintainer権限の付与をお願いしたいです。
メンテナじゃないとPull Requestにコミット積めなくて活動に支障が出そうです。

owner権限までは必要ないと思っています。

**Comment by m-tmatma** [comment]
`Allow members to delete or transfer repositories for this organization` のチェックを外してみました。

### 変更前

<img width="1045" alt="privilege" src="https://user-images.githubusercontent.com/5567450/45925604-d1ed9800-bf53-11e8-85b5-e50f5acd89e9.png">

### 変更後

<img width="1045" alt="privilege2" src="https://user-images.githubusercontent.com/5567450/45925629-327cd500-bf54-11e8-8590-855166df0ddd.png">

**Comment by m-tmatma** [comment]
以下のチェックも外しました。

```
Allow members to change repository visibilities for this organization

If enabled, members with admin permissions for the repository will be able to change repository 
visibility from public to private. If disabled, only organization owners can change repository visibilities. 

```

**Comment by m-tmatma** [comment]
> maintainer権限の付与をお願いしたいです。

approve しました。

> `Allow members to delete or transfer repositories for this organization` のチェックを外してみました。

`Delete this repository` は出ますか?

**Comment by berryzplus** [comment]
ありがとうございます。

> Delete this repository は出ますか?

ボタンが消えています。

そのテーブルで有効なのは archive this repository だけです。

**Comment by m-tmatma** [comment]
完了したので閉じます
