### ISSUE TITLE
旧掲示板を参照オンリーへ

### ISSUE THREAD

**Issue by KENCHjp** [sakura-editor/management-forum#39]
Cyclamenを参照オンリーへ変える方法ご存知の方いますか？

**Comment by berryzplus** [comment]
`cyclamen.cgi` を弄ったらいいのかな・・・。
掲示板のアドレスが `http://sakura-editor.sourceforge.net/cgi-bin/cyclamen/cyclamen.cgi`なので。
拡張子 cgi だと Perl っぽいので、ソースコードさえ触れればなんとかなりそうに思います。

ここのサイトのソースをどうやって取るか、ぼくは分かっていないです。

前に @kobake さんがmaruさん（サイト管理してた方）とはメール連絡付いたと書いてた気がします。
@kobake さんが maru さんから方法を引き継いでいたらきっと反応してくれるはず・・・

ちょっと待ってみてダメそうならmaruさんに訊いてみる、になるのかな・・・。

**Comment by KENCHjp** [comment]
ソースはsourceforge.netのアカウントがあればSCPでとってこれます。
でパスワードが入っているcgiファイルがあるんですがハッシュ値なので元のパスワードがわかりません。
CGIを修正するのはバグりそうなので手は付けたくないかなと思っております。
dataファイルがある場所は見つけたので最悪ReadOnlyにすればいいのかななんておもうのですが、
最初に書き込みチェックとかしてたらCGI動かなくなりそうなので怖くてやれてないんです^^;

**Comment by berryzplus** [comment]
> ソースはsourceforge.netのアカウントがあればSCPでとってこれます。
でパスワードが入っているcgiファイルがあるんですがハッシュ値なので元のパスワードがわかりません。
> CGIを修正するのはバグりそうなので手は付けたくないかなと思っております。
> dataファイルがある場所は見つけたので最悪ReadOnlyにすればいいのかななんておもうのですが、
> 最初に書き込みチェックとかしてたらCGI動かなくなりそうなので怖くてやれてないんです^^;

そういう話であれば、送信ボタンを押せなくするだけの対応をしたらいいのでは？と思います。

```html
<input type="submit" value=" 送    信 ">
```
　　　　↓
```html
<input type="submit" value=" 送    信 " disabled="disabled">
```

`s/submit/` でヒットしたすべての送信ボタンを無効にしておけば、バグ混入の可能性を抑えつつ、書込みを無効にできるような気がします。まぁ、その状態について美的感覚から突っ込みをする人はいそうですけれども :smile:

**Comment by KENCHjp** [comment]
一応、アカウント一覧のテキストファイルを見つけるも、肝心の掲示板だけは管理者パスワードの記載がない。。。

**Comment by berryzplus** [comment]
> 一応、アカウント一覧のテキストファイルを見つけるも、肝心の掲示板だけは管理者パスワードの記載がない。。。

書き込み時に設定する削除パスワードを保存しておくファイルのような気がしました。
投稿者が設定するものだから、管理者の分はない、という理屈なのかな、と。

**Comment by KENCHjp** [comment]
>管理者の分はない、という理屈なのかな、と。

CGI及びファイル名を見る限り管理者パスワードを暗号化して格納しているもようです。

**Comment by berryzplus** [comment]
> CGI及びファイル名を見る限り管理者パスワードを暗号化して格納しているもようです。

(;￣Д￣)なんじゃと？

ソースコード見たほうがいいですかね。

CGI修正箇所のイメージはこんな感じ

場所 | 修正箇所数 | 修正内容
---- | ---- | ----
各掲示板のトップ | 4(=掲示板の数) | [新規投稿] のリンクを非表示にする
投稿ページ | 1 | 送信ボタンを無効にする
POSTハンドラ | 1 | 無条件で404(Not Found)を返すように細工する

**Comment by KENCHjp** [comment]
>各掲示板のトップ

変更しようとおもえば、削除ボタンとかもありますが削除することはないかと思うので、
新規投稿のリンクを非表示するだけでいいような気がしてきました。

一般の人ならそれで書き込み諦めるかと思うし。

**Comment by KENCHjp** [comment]
実は２件ほど追加書き込みあるんですよねぇ。

**Comment by KENCHjp** [comment]
CGIに閲覧専用モードがあるのを発見、データのどっかのフラグをOnに出来ればよさそう。

**Comment by berryzplus** [comment]
> 実は２件ほど追加書き込みあるんですよねぇ。

read only 対応終わったあとで考えましょ :smile:

よくよく考えてみたら「新規投稿」のリンク先を OSDN フォーラムに差し替えるのもよいような気がしてきました。なんか１つ、移転先がないのがあった気がしますけど、こちらの意図として投稿してほしくないわけではないので「投稿できる場所に飛ばす」がいいような。

**Comment by berryzplus** [comment]
> CGIに閲覧専用モードがあるのを発見、データのどっかのフラグをOnに出来ればよさそう。

おおお。

**Comment by KENCHjp** [comment]
場所みっけ！
とりあえず、やってみます。ちとビビる(笑)

**Comment by KENCHjp** [comment]
あかん、cgiの所有者がげんたさんで、パーミッションが755。
詰む。。。

**Comment by KENCHjp** [comment]
あれ、でも、前ってみんなで更新してたんじゃないかなぁ、CGIって。もうちょっと調べてみます。

**Comment by KENCHjp** [comment]
とりあえず、cgiは更新できそうですが、肝心のReadOnlyフラグを持っているファイルがなぜか更新できない。。。
フォルダで何か権限ついてるみたい、確かデータの喪失防止でなんかやってた気がする。。。

**Comment by berryzplus** [comment]
がんばれ～的なニュアンスのemo iconがないことに気付く、など :cry:

**Comment by KENCHjp** [comment]
しょうがないので、更新できるcgi本体側でreadonly変数を無理やり立てればいいんじゃねって思ってきたが、perlが怪しいので、今日やるかどうか思案中。

**Comment by KENCHjp** [comment]
でけたみたいwww。configファイル読んでる関数を呼んでるところの直後で、readonlyフラグを無理やり立てる策!

**Comment by KENCHjp** [comment]
副産物で、 http://sakura.qp.land.to/ ここのパスワード見つける(笑)

**Comment by berryzplus** [comment]
新規投稿ボタンが消えたのを確認 :smile:
http://sakura-editor.sourceforge.net/cgi-bin/cyclamen/cyclamen.cgi?log=data

**Comment by KENCHjp** [comment]
サクラエディタ アップローダ その２ってのを初めて見つける。スパム消した方がいいんだろうか。

**Comment by KENCHjp** [comment]
>新規投稿ボタンが消えたのを確認 😄

俺、がんばった!

**Comment by KENCHjp** [comment]
というわけで、ここ閉じます。
