### ISSUE TITLE
GitHubからのメール来ました？

### ISSUE THREAD

**Issue by KENCHjp** [sakura-editor/management-forum#42]
GitHubからこんなメールが、

---
A GitHub App, WIP, installed on your organization, sakura-editor, is requesting updated permissions.

Visit https://〜〜一旦URL隠し〜〜 to review and accept or deny these permissions.

You can view pending requests directly by visiting your organization’s settings page and clicking on Applications. If you run into problems, please contact support by visiting https://github.com/contact.

Thanks,
Your friends at GitHub
---

来たのですがはてやっていいものでしょうか？

リンクの先は、

Read & write access to Checks New request
Read-only access to Single file New request
Path: .github/wip.yml
Read & write access to Pull requests Was read-only

で unchanged permissions
Read & write access to Commit statuses

とのことだそうですが。

**Comment by m-tmatma** [comment]
前に有効にした wip のgithub    アプリです。
スルーしてました。
またあとで見ます。

**Comment by KENCHjp** [comment]
m( _ _ )m

**Comment by berryzplus** [comment]
来ましたよー。詳しく見てないだすけど。

**Comment by m-tmatma** [comment]
WIP のアプリが更新されて、GitHub の market place のアプリになって
https://github.com/marketplace/wip

新しい権限を要求するようになったから、許可して、という趣旨ですね。
https://github.com/wip/app/issues/89#issuecomment-432447327

**Comment by KENCHjp** [comment]
>という趣旨ですね。

やっちゃってよい？

**Comment by m-tmatma** [comment]
いいと思います

**Comment by KENCHjp** [comment]
やってみました。

**Comment by KENCHjp** [comment]
https://github.com/organizations/sakura-editor/settings/installations

WIPがpendingになってるようですが出先で触れず。。。

**Comment by m-tmatma** [comment]
> 新しい権限を要求するようになったから、許可して、という趣旨ですね。
> [wip/app#89 (comment)](https://github.com/wip/app/issues/89#issuecomment-432447327)

許可しました。

**Comment by KENCHjp** [comment]
あざっす。

**Comment by KENCHjp** [comment]
閉じます。
