### ISSUE TITLE
ダウンロードページでダウンロードしようとすると、XMLファイルが表示されダウンロードできない。

### ISSUE THREAD

**Issue by KENCHjp** [sakura-editor/management-forum#45]
https://github.com/sakura-editor/sakura/releases/tag/v2.3.2.0

とかのzipのリンクをクリックすると、

```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>～省略～</Key>
<RequestId>～省略～</RequestId>
<HostId>
～省略～
</HostId>
</Error>
```
こんな表示になりダウンロードできないようです。ひとまず一報。

**Comment by KENCHjp** [comment]
exeだけみたいですね。ソースのほうのzipはダウンロードできます。
何かの検閲引っかかった？

**Comment by KENCHjp** [comment]
URL見るとAWSのS3にリダイレクションしてるみたいですね。

**Comment by ds14050** [comment]
ダウンロード元が書かれていたのでとりあえず 2.2.0.0 に再アップロードしてみました。同じ名前が使えなかったので (re-up) 版として下書き保存しています。

このまま元ファイルへのリンクを削除して、(re-up) を削り、リリースとして保存していいものなのでしょうか。

**Comment by KENCHjp** [comment]
原因がわからないので前のは残しておきたいですね。
＆再発するかもしれんし。
今日ちょっとさわれそうにないので私やるとすると明日になりまする。

**Comment by KENCHjp** [comment]
スタッフだれかがバケット削除しちゃったのか、セキュリティソフトみたいなのが走って隔離されちゃったか。
GitHubサポートリクエストかとおもっとります。
S3ならログ残ってると思う＆バックアップから戻せるやも。

**Comment by ds14050** [comment]
一度消えてしまったリポジトリのリリースファイルなので関連ファイルも掃除されてしまったのかと考えました。

それだと zip 以外のソースコードへのリンクが有効なまま残っているのが不思議だったのですが、[Edit release] してみるとわかるように、ソースコードへのリンクは編集対象ではありませんでした。

ユーザーがアップロードしたファイルが掃除対象になったというのは十分考えられることです。

**Comment by KENCHjp** [comment]
了解です。いろいろありがとうございます、@ds14050 さん。

また私の流暢なGoogle翻訳炸裂させます！

**Comment by KENCHjp** [comment]
とりあえずメールでサポート依頼しました。
音沙汰なかったらGoogle翻訳の英語力を恨みつつ再度メールします。

**Comment by KENCHjp** [comment]
再度メールするもとりあえずまだ返事なし、今日の遅くが現地の月曜日かな。
今日までまってなにもなければ再アップロードしようかなと。

**Comment by KENCHjp** [comment]
返事が来た。

```
Hi KENCHjp,

Sorry for the trouble! We experiences some server issues around this time which I believe may have been related.

Would it be possible to upload the file again to the Release?

I'm hoping this corrects things but please let us know if this doesn't work. 

Cheers
Stacey 
```

てことで、再度アップロードしましょう。

**Comment by m-tmatma** [comment]
次のリリースするときは、バイナリのハッシュを記録した上で、github  以外にもリリースバイナリを置いたほうがいいですね。

**Comment by KENCHjp** [comment]
>次のリリースするときは、バイナリのハッシュを記録した上で、github 以外にもリリースバイナリを置いたほうがいいですね。

一応今、OSDNにアップロードしています。
https://ja.osdn.net/projects/sakura-editor/releases/
アップロードするとハッシュは自動で計算されます。

**Comment by KENCHjp** [comment]
GitHubはアップロードしなおして、コメントにmd5のハッシュを記述しました。
