### ISSUE TITLE
Permalink が展開されない件に関して GitHub に問い合わせ

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/management-forum#46]
Permalink が展開されない件に関して GitHub に問い合わせ
(https://github.com/sakura-editor/sakura/issues/592#issuecomment-435390390)

```
If we had inserted a parmalink to an issue, the content of the link would be expanded inline.
(example: https://github.com/sakura-editor/sakura/issues/398#issuecomment-418045277)

But it doesn't be expanded now.
(example: https://github.com/sakura-editor/sakura/issues/592)

Is it a bug? If so, please fix it at your earliest possible convenience.
If it is intentional, please explain why such specification change has made.

```

**Comment by m-tmatma** [comment]
返事返ってきた。

この問題を認識しているし、修正中だけど、直すのにどのぐらい時間がかかるかわからない。
でも任せてくれ、みたいな内容です。

ETA(Estimated time of arrival)
https://juken.oricon.co.jp/rank_english/news/2090164/

in good hands
https://eow.alc.co.jp/search?q=in+good+hands


```
Hello there,

Thanks for writing in about this and I'm sorry for the trouble. 
This is due to an issue on our side that our team are aware of and working on.

I don't have an ETA on a fix right now but this is in good hands. 
I've also made a note to follow up with you once this is resolved.

Please let me know if you have any other questions in the meantime.
```

**Comment by KENCHjp** [comment]
>でも任せてくれ、

かっけー。

**Comment by m-tmatma** [comment]
直った? あれ? どのぐらいかかるかわからないと返したばかりなのに? 全部は直ってないのかな?
https://github.com/sakura-editor/sakura/issues/598

**Comment by m-tmatma** [comment]
こっちは直ってない
https://github.com/sakura-editor/sakura/issues/592

**Comment by berryzplus** [comment]
そのセリフ、先に言われた感全開 :smile:

**Comment by m-tmatma** [comment]
> こっちは直ってない
> [sakura-editor/sakura#592](https://github.com/sakura-editor/sakura/issues/592)

直ったみたい

**Comment by m-tmatma** [comment]
何か新たに issue 作成して、問題ないようであれば閉じてもいい

**Comment by m-tmatma** [comment]
https://github.com/sakura-editor/sakura/issues/628
で動いたので閉じる。

**Comment by ds14050** [comment]
細かい話。permanent link の略なので permalink ではないかと思う。merge も間違えそうになる。

**Comment by m-tmatma** [comment]
直しました。恥ずかしー。
