### ISSUE TITLE
雑談場Part3

### ISSUE THREAD

**Issue by ds14050** [sakura-editor/management-forum#47]
Part1 #14
Part2 #38

**Comment by berryzplus** [comment]
ずざーーーってした方がいいですか？

**Comment by KENCHjp** [comment]
スレ立て乙。

**Comment by KENCHjp** [comment]
そっか上にでてたのね。じゃあ、60近くで次にしましょう！

**Comment by m-tmatma** [comment]
ポイントカードはお持ちですか？ と聞かれたら…
https://www.ponta.jp/c/applewallet/

**Comment by m-tmatma** [comment]
ターミネーター は 8bit cpu らしい
https://t-cul-club.hatenablog.com/entry/2018/11/10/010521

**Comment by m-tmatma** [comment]
こんな記事あった
https://www.mag2.com/p/news/376210

**Comment by ds14050** [comment]
中国は大国としての王道を行こうとしていますよね。一方の日本は「一番でなければダメなんですか」が問われる国です。

**Comment by ds14050** [comment]
しばらく前から気になっているのですが、appveyor.yml のこの行が何の目的で存在しているのか不思議です>https://github.com/sakura-editor/sakura/blob/efcaef1436281a5255f258ecc246f449164ddf74/appveyor.yml#L21

また、同じファイルでバージョン番号を指定している１行目ですが、意味のないバージョン番号(1.0.X)で AppVeyor のアカウントでの設定を上書きしてしまうので、またメンテナンス対象を絞る意味でも、削除してしまいたいなーと機会を窺っています。

**Comment by m-tmatma** [comment]
> しばらく前から気になっているのですが、appveyor.yml のこの行が何の目的で存在しているのか不思議です>https://github.com/sakura-editor/sakura/blob/efcaef1436281a5255f258ecc246f449164ddf74/appveyor.yml#L21

試行錯誤していたころの残骸です。
https://github.com/sakura-editor/sakura/pull/617
送りました。

**Comment by m-tmatma** [comment]
> また、同じファイルでバージョン番号を指定している１行目ですが、意味のないバージョン番号(1.0.X)で AppVeyor のアカウントでの設定を上書きしてしまうので、またメンテナンス対象を絞る意味でも、削除してしまいたいなーと機会を窺っています。

デフォルトで appveyor 上の設定で `1.0.{build}` になっています。(今もそうです)
最初に appveyor.yml を作ったときに設定を yml にエクスポートして作ったので
その設定になっています。

以前は この version の設定が appveyor のビルドの URL の一部になっていたので
途中で URL が変わることを避けるために、変更しませんでした。

**Comment by ds14050** [comment]
バージョン指定は現在は不要、と。

**Comment by berryzplus** [comment]
コメント中の誤字に気付いて、こっそりrebaseするなう。。。

**Comment by berryzplus** [comment]
たとえ無責任だったとしても、的確なツッコミは助かるんですよ。

と、どっかの掲示板に書きかけてやめたなう。。。

**Comment by berryzplus** [comment]
そういえば 15.9.2 がリリースされたようで。
https://docs.microsoft.com/ja-jp/visualstudio/releasenotes/vs2017-relnotes

**Comment by m-tmatma** [comment]
@berryzplus さん

https://github.com/sakura-editor/sakura/issues/446#issuecomment-441044867

で以下のように書かれていますが、

> そろそろ少しずつ試験運用をしてみてもいいかな～と思い始めました。
> 個人アカウントを用意できる人で「色々やってみる」を試験運用と言ってます。
> 結果は **できるだけここに書く** というスタンスでまずはやってみようってことです

https://github.com/sakura-editor/sakura/issues/446 のチケットは
vtbassmatt さんが見ているので、vtbassmatt さんに見てほしい情報以外は
違う場所に書く方がいいと思っています。

> さっき `Microsoft Azure` のアカウント登録してきました。
> https://azure.microsoft.com/ja-jp/features/azure-portal/

またおそらく、`Microsoft Azure` と `Azure Pipelines` は別のサービスだと思います。
`Microsoft Azure` はもともとあった有料の cloud サービスですが、
`Azure Pipelines` は最近できた (もう最近でもないですが) 無料のプランも
選べるcloud のCIサービスだと思います。

**Comment by berryzplus** [comment]
> vtbassmatt さんが見ているので、vtbassmatt さんに見てほしい情報以外は
違う場所に書く方がいいと思っています。

意図了解。一応、使い始めてみます、という遺志表示をする目的があったのであそこに書きました。

**Comment by berryzplus** [comment]
appveyorのログ量が、認識していた量の3倍くらいになってるような
https://ci.appveyor.com/project/sakuraeditor/sakura/builds/20525216/job/dpvywdmsma8wjwo5

3倍でつい喜んでしまうと素性が割れるわけですが・・・ﾐﾄﾒﾀｸﾅｲｯ

**Comment by m-tmatma** [comment]
> appveyorのログ量が、認識していた量の3倍くらいになってるような
> https://ci.appveyor.com/project/sakuraeditor/sakura/builds/20525216/job/dpvywdmsma8wjwo5
> 
> 3倍でつい喜んでしまうと素性が割れるわけですが・・・ﾐﾄﾒﾀｸﾅｲｯ

そのために https://github.com/sakura-editor/sakura/pull/635 があります。

**Comment by m-tmatma** [comment]
[Don’t let perfect be the enemy of good](http://d.hatena.ne.jp/Mickie_Grace/20091206)

BS テレビ東京でこの言葉を紹介した。

**Comment by m-tmatma** [comment]
[monopoly (モノポリー)](https://ejje.weblio.jp/content/monopoly) って独占という意味らしい。

**Comment by KENCHjp** [comment]
>Don’t let perfect be the enemy of good

まさしくこんなプロジェクトを経験しました。「いいかげん」は難しいです。

**Comment by ds14050** [comment]
PR 画面からレビューリクエストが出せますが、あれはメンバーを表示しているのではなく、Suggestions とあるように、レビューに適すると GitHub が考える人だけが挙がるようですね。

ファイルのログからコミット作者かコミッターを見ているのでしょうか。

**Comment by KENCHjp** [comment]
しわぁ～っす。

**Comment by berryzplus** [comment]
12月になりましたね・・・

C++関連の有名な人に[ビャーネ・ストラウストラップ](http://www.stroustrup.com/)という人がいるんです。昔なんかの書籍の奥付であごひげをフッサフサに伸ばした写真が載っていて、そのイメージが強いです。

12月になって例の赤い服のおっさんもどきが街に現れると、あのフッサフサな「お髭」を思い出してしまう・・・。今のご時世、昔の写真は見つかりませんでした。初期のC++関連の書籍だと思うんですが、探してみると面白いかも知れません。

**Comment by berryzplus** [comment]
昨日、ちょっと高いマウスを買ってみたんですが、使いやすさ半端なくて驚いています。

https://www.amazon.co.jp/Logicool-ロジクール-MX2100sGR-ワイヤレスレーザーマウス-Bluetooth/dp/B071Z2TFHX/ref=sr_1_4_sspa?s=computers&ie=UTF8&qid=1543669375&sr=1-4-spons&keywords=logicool+anywhere+2s&psc=1

昔は秋葉原で買った500円マウスの玉外して掃除したりしたもんですが・・・

**Comment by m-tmatma** [comment]
> 昨日、ちょっと高いマウスを買ってみたんですが、使いやすさ半端なくて驚いています。

高! と思ったけど、(販売価格は) Apple の `Magic mouse 2 ` と変わらない。

**Comment by m-tmatma** [comment]
> 「いいかげん」は難しいです。

激しく同意します。

**Comment by KENCHjp** [comment]
> >「いいかげん」は難しいです。

> 激しく同意します。

そうなんっすよねぇ、仕事なので「いいかげん」にやるつもりはないのですが、C2メジャーを要求してくるような客（「ダウンタイムゼロ」とか、「AWSのS3の可用性が99.99%で100%じゃないのでテープにも取らないと」とか、「RPO/RTOは０」とか）は平気でいます。
「良い加減」の線引きは難しいです。

**Comment by m-tmatma** [comment]
4K 放送始まりましたね。

電器屋に4k 放送見に行った。

4K チューナー内蔵のテレビで 4K 放送見てたら
店員さんが話しかけてきて、どのサイズをお探しでしょうか？と聞いてきたので
正直に、4K 放送見にきただけです、と言ったら去っていった。

**Comment by KENCHjp** [comment]
https://ja.osdn.net/projects/sakura-editor/stats/frs/?from=2018-05-01&to=2018-12-03&group_id_id=10965&mode=country&graph=geo

![default](https://user-images.githubusercontent.com/39618965/49346613-59841f80-f6d8-11e8-82c9-2b8c22a6970e.PNG)

OSDNからの昨日までのダウンロード数。

**Comment by berryzplus** [comment]
うずうず・・・。
もしかしてご本人様ですか？と訊きたい気持ちで一杯ですがあえて熱くスルー :sob:

**Comment by KENCHjp** [comment]
登録セキスペの集合教育受けてきました。
久々社外の人とグループディスカッションして楽しかったっす。

**Comment by berryzplus** [comment]
[セキスペ](https://www.ipa.go.jp/siensi/)・・・そういうのあるんですね。
最近の国家資格なんも取ってないっす。

10年くらい前に、警察だか自衛隊だかで、なんかの有資格者を経験者待遇で受け入れるって話があったときにちょっと調べたのが最後かなぁ・・・

**Comment by KENCHjp** [comment]
>セキスペ・・・そういうのあるんですね。

情報処理の高度情報セキュリティの延長みたいなやつですね。
更新するのに、毎年オンライン教育２万、３年に一度集合教育８万必要です。。。

**Comment by KENCHjp** [comment]
遅い夏休みを今週いただいております。PC新調して引っ越し中。。。

**Comment by berryzplus** [comment]
今年の漢字「災」って…

**Comment by m-tmatma** [comment]
アメリカ政府で使用しているコードが、 github で管理されているらしい。
https://blog.github.com/2018-11-09-happy-birthday-codegov/

**Comment by berryzplus** [comment]
アメリカの政府組織っていうとCIAとかFBIを想像しちゃいますけど、NASAなんですね。
日本で言うとCIAは公安、FBIは警視庁で、NASAは[JAXA](http://www.jaxa.jp/)。
研究開発機関のプロジェクトなら公開可能で、半端ない数になるのも納得・・・。

**Comment by ds14050** [comment]
警視庁は東京都警以上のものでしたか。

**Comment by berryzplus** [comment]
警察庁ってあるんでしたっけ？ｗｗ
よく間違えます。

**Comment by ds14050** [comment]
警視庁が主導的な役割を担っていることは否定できませんし、警察庁が捜査を行うかどうかもわかりません。日本で広域的な捜査を担うのはどこでしょうね。

検察庁？ 特別捜査部？

**Comment by m-tmatma** [comment]
タネなっぴー
https://www.yokohamaueki.co.jp/news/745

テレビで紹介してた。

**Comment by m-tmatma** [comment]
grammarly というサービスがあるみたい。
http://lifeiscolourful.hatenablog.com/entry/grammarly-n-writing

**Comment by berryzplus** [comment]
最近ルー語もいいなとか。

**Comment by m-tmatma** [comment]
パスポートのデザインが変わるらしい
https://www.mofa.go.jp/mofaj/ca/pss/page23_002805.html

**Comment by m-tmatma** [comment]
もう次の話が‥
https://pc.watch.impress.co.jp/docs/news/1158093.html
https://pc.watch.impress.co.jp/docs/column/kaigai/1158759.html

**Comment by beru** [comment]
変数宣言の強制は一般ユーザーにはしなくては良いのではないか説
https://blog.goo.ne.jp/santaro2006/e/85f40634bde727619e5b7fa31436c6b0

という事は C++17 から入る `std::variant` で `a` から `z` までの extern グローバル変数を用意してローカル変数と引数を使わなくなるプログラミングが流行る可能性も？？

**Comment by m-tmatma** [comment]
放送大学(最近名前変わった？)の数学の講義で、N を ラージエヌと言ってたので、うん？ と思ったので調べてみた。
https://blog.goo.ne.jp/kano08/e/b944166474479a707324cdecc1cabc83

**Comment by m-tmatma** [comment]
ruby 2.6 が出たらしい
https://forest.watch.impress.co.jp/docs/news/1160255.html
https://www.ruby-lang.org/ja/news/2018/12/25/ruby-2-6-0-released/

**Comment by arigayas** [comment]
[サクラエディタ - Wikipedia](https://ja.wikipedia.org/wiki/%E3%82%B5%E3%82%AF%E3%83%A9%E3%82%A8%E3%83%87%E3%82%A3%E3%82%BF) の記述が2017年6月8日から更新されていなくて
古いので書き換えようかなと思ったのですがURL以外で何か書き換える事はありますか？

**Comment by KENCHjp** [comment]
>何か書き換える事はありますか？

@arigayas さん、いつもありがとうございます。
特にリクエストはないので現時点矛盾が感じられるところとかがあれば修正いただければと思います。
っていうか私がやってもいいのですがWikipediaを直接更新したことがなくお作法とかよくわかってなかったりw

**Comment by arigayas** [comment]
実は文章を考えるのが苦手なので**ここは直しておいて欲しい**点がヒントになるかも？と思って聞いてみました。

とりあえず公式サイトがGitHubに移行したことだけ変更しておきますね。

**Comment by arigayas** [comment]
> とりあえず公式サイトがGitHubに移行したことだけ変更しておきますね。

Done

**Comment by ds14050** [comment]
ワオ。初めて見た(笑)>「サクラエディタ - Wikipedia」

**Comment by arigayas** [comment]
> ワオ。初めて見た(笑)>「サクラエディタ - Wikipedia」

Wikipediaへのリンクを貼った意味がありましたw

**Comment by berryzplus** [comment]
あけましておめでとうございます。
とうとう2019年が始まりました。
2019年がみなさまにとっていい年になりますように :smile:
今年もよろしくお願いします。

**Comment by ds14050** [comment]
berryplus さん、大人ですね。座布団３枚分上に上げておきました。

**Comment by KENCHjp** [comment]
あけましておめでとうございます。

今年と来年は祝日が変則なのでみなさんご注意を(笑)

今朝早起きしたら三日月と金星がほぼ隣り合わせに輝いておりました☽☆

**Comment by KageShiron** [comment]
私は親元に帰って規則正しい生活に戻ろうとしています 😅 
それでも起きられないけど

**Comment by m-tmatma** [comment]
無料になるらしい
http://www.itmedia.co.jp/news/articles/1901/08/news051.html

**Comment by m-tmatma** [comment]
だからどうしたという話なんだけど。こんな瞬間はこないかもしれない。

![sakura-status](https://user-images.githubusercontent.com/5567450/51070716-49713f80-1689-11e9-9bcb-e5d683b3051d.png)

**Comment by berryzplus** [comment]
30/300/30 ... 揃いましたねぇ・・・

この数字の意味がよく分ってないんですが、
左側の数字が大きいほど注目されてるってことでいいんでしたっけ。
「ウォッチ数/Star数/fork数」だから。

**Comment by m-tmatma** [comment]
"期待する" のいろんな表現
https://eikaiwa-highway.com/hope-expect/

**Comment by berryzplus** [comment]
> I wish that I didn’t have to work the rest of my life.
> 
> 残りの人生、働く必要がなければいいのに。

とりあえず激しく同意してみたけど、そういうこっちゃないですよね・・・。

**Comment by m-tmatma** [comment]
みんなもっと早く寝たらいいんじゃない?
働きすぎなんじゃない?

**Comment by berryzplus** [comment]
上のコメントをチラ見しつつ、こんな時間にコメントします。

カラーマーカーの件はもう少し放置っす。

* これ何？
* ブックマークや検索と何が違うの？
* なんで拡張じゃなく新規なの？

といった素朴な疑問に答えられる人がたぶん居ないのが理由です。
ぼくが勝手に答えを出して行くと、最終的に「カラーマーカー」という新機能は消滅しそうな気がします。実装内容を要約するとブクマと検索ハイライトの機能強化なので、素直にそういう実装に書きなおすと「カラーマーカー」はなくなってしまうと思うんです。

ただ、そういう結論にするのはなんか違う気がするので、もうちょっとマシな提案を思いつくまで放置しよっかなーと思ってます。
