### ISSUE TITLE
誰がマージすべきか?

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/management-forum#49]
誰がマージすべきか?
https://github.com/sakura-editor/sakura/pull/591#issuecomment-437367189

`merge` `誰` `approve` をキーワードに google で検索したところ以下のページが見つかった。
https://github.com/CIR-KIT-Unit03/cirkit_unit03_whole_issue/issues/7

上記では、Pull-requestを出した人で落ち着いたみたいです。
Pull-requestを出した人がメンバーである場合に限定されますが。

**Comment by KENCHjp** [comment]
>上記では、Pull-requestを出した人で落ち着いたみたいです。
>Pull-requestを出した人がメンバーである場合に限定されますが。

この認識です。プロジェクトメンバー外の人のRPだとAdminメンバーっすかね。メンバーであればだれでもいい気もします。
各メンバー得手不得手あるやもしれないので。

**Comment by ds14050** [comment]
結論ではなく結論に至る観点を見ましょう。
* マージ後に発生する問題に即応できる適任者は誰か
* うっかり WIP を付け忘れた PR をマージする危険を回避できる

という観点からその結論に至ったようです。適任者を責任者と読み替えれば(※特に担当領域が決められているわけではないサクラエディタプロジェクトではほぼ同じ意味です)、自分の考えと変わりません。

**Comment by ds14050** [comment]
* 「[Pull Request をマージするのは誰だ - Qiita](https://qiita.com/numa08/items/8486b53daa5f159d710a)」
  PR を出した人。理由に複数言及あり。「自分に割り当てられている Issue を自分で終了できる」「rebaseとの相性が良い」「責任の所在がはっきりとする」
* [GitHubを使うなら最低限知っておきたい、プルリクエストの送り方とレビュー、マージの基本 (2/2)：こっそり始めるGit／GitHub超入門（10） - ＠IT](http://www.atmarkit.co.jp/ait/articles/1702/27/news022_2.html)
  ルール次第だが PR を出した人。「誰がプルリクエストをマージするかは、開発チームのルールによります」「筆者が所属するチームの場合、プルリクエストは以下のフローで行うことが多いです」「4. マージできる状態になったら、実装者が「Merge pull request」ボタンを押してマージを行う」
* [GitHub FlowとPull Request駆動開発をYWTでふりかえり - Splash of waters - 2nd. Season](https://jappy.hatenablog.com/entry/2015/06/21/031440)
  PR を出した人。コンフリクトを解消することとマージを一体的に行ううえでの適任者ということらしい。「マージするのはレビュアーでなく依頼者（コード書いた人）」「マージする人の責任でコンフリクトを解消します」

**Comment by berryzplus** [comment]
元も子もない意見かも知れませんがぼくの意見を書いておきます。

結論
・やりたい人がマージすべきです。

補足
・やりたい人が複数いる場合は競合が起きます。
その場合の優先順位は1=PRを出した人、2=レビュアー以外のメンテナ、3=レビュアーだと思います。

自分が関わったものは、きっと自分でマージしたいはずだ、という勝手な思い込みに基づくものです。そうじゃない人がいるかも知れません。@ds14050 さんは自分でやりたい派だと思います。ぼくも多分にそういう部分があります。

やりたい人がマージしよう！でいいんじゃないかな、と思います。

**Comment by ds14050** [comment]
やりたい人やりたい人では誤解を招くので、berryzplus さんに代わって berryzplus さんの意見をまとめましょう。

0. 前提。マージする義務を負っている人はいない(強いていえば 3 のレビュア)。
1. PR を出した人が最優先
2. 対象分野の面倒を見ている人が２番
3. 関わった誰かが最後の責任を引き受ける

サクラエディタでは今のところ２番の役目を負っている人はいないと思います(あるいはファイルの新規作成者やコミットが多い人が当てはまるのかもしれません)。

リストに特に異存はありません。

**Comment by m-tmatma** [comment]
私は誰がマージしてもいいと思います。
PR を出した人でも、レビューした人でも、それ以外の人でもいいと思います。

PR を出した人は、一番詳しいはずですが、
レビューした人は、チェックして ok を
出したので、最低二人が大丈夫と判断したからですし、レビュアー以外でもマージするからには内容を多少なりとも確認しているはずだからです。

誰がマージするかより、approve されてから、実際にマージするまでに多少の時間を置くのが大事だと思います。

レビューに参加してない人が、マージ後にコメントを書くことがたまにあるからです。

**Comment by ds14050** [comment]
>レビューに参加してない人が、マージ後にコメントを書くことがたまにあるからです。

何度かそういうことをしている自分の事情です。

* PR に関係するバグが見つかったときに報告する既存の場として。
* 週末には時間がとれないのだが、初めて見た時にはもうマージまでの一連のサイクルが完了していた。

**Comment by berryzplus** [comment]
> 1. PR を出した人が最優先
> 2. 対象分野の面倒を見ている人が２番
> 3. 関わった誰かが最後の責任を引き受ける

責任分散の感覚値は 4 : 4 : 2 です。

**Comment by ds14050** [comment]
>責任分散の感覚値は 4 : 4 : 2 です。

2 の人の存在感の大きさで 1 と 2 の具体的な比率は変わってきそうです。

**Comment by KENCHjp** [comment]
1. 前提。マージする義務を負っている人はいない(強いていえば 3 のレビュア)。
2. PR を出した人が最優先
3. 対象分野の面倒を見ている人が２番
4. 関わった誰かが最後の責任を引き受ける

この方向に賛同、まケースバイケースで、「俺がマージしたい」って人もいるかもしれませんし。
最初にPR出した人から、途中変更されて、自分の意図しない方向になってったら、取り込まれるより自分で破棄したいかもしれないし。

**Comment by m-tmatma** [comment]
PR を出した人がマージするというのが定着してきたので閉じます。
