### ISSUE TITLE
VSCodeのバグ？

### ISSUE THREAD

**Issue by KENCHjp** [sakura-editor/management-forum#55]
VSCodeのバージョン1.29.1だと、Markdown TOCで目次つくると、
autoって文字がごちゃて入ってきて目次がきれいに作れないっす。。。
古いPCで1.28???ぐらいだったとおもうけど、それでは壊れず、バージョンアップしたら、
案の定壊れる。。。

**Comment by m-tmatma** [comment]
バグ報告されてますね。
https://github.com/AlanWalk/markdown-toc/issues/65

**Comment by m-tmatma** [comment]
↑ 一応ワークアラウンドは提示されているみたい

**Comment by KENCHjp** [comment]
おお、治った！

**Comment by m-tmatma** [comment]
https://github.com/sakura-editor/sakura/wiki/GitHub-Tips:-Markdown-%E3%81%AB%E5%AF%BE%E3%81%97%E3%81%A6%E7%9B%AE%E6%AC%A1%E3%82%92%E4%BD%9C%E3%82%8B%E6%96%B9%E6%B3%95
に足しておきました。

**Comment by m-tmatma** [comment]
https://github.com/AlanWalk/markdown-toc/issues/65#issuecomment-448922438

直っているらしい

**Comment by m-tmatma** [comment]
> [AlanWalk/markdown-toc#65 (comment)](https://github.com/AlanWalk/markdown-toc/issues/65#issuecomment-448922438)
> 
> 直っているらしい

最新版を再インストールしたが、治ってなさそう。

**Comment by m-tmatma** [comment]
https://github.com/sakura-editor/sakura/wiki/GitHub-Tips:-Markdown-%E3%81%AB%E5%AF%BE%E3%81%97%E3%81%A6%E7%9B%AE%E6%AC%A1%E3%82%92%E4%BD%9C%E3%82%8B%E6%96%B9%E6%B3%95
のページで回避方法の手順のスクリーンショットを貼り付けました。

**Comment by m-tmatma** [comment]
> VSCodeのバージョン1.29.1だと、Markdown TOCで目次つくると、
> autoって文字がごちゃて入ってきて目次がきれいに作れないっす。。。

[GitHub Tips: Markdown に対して目次を作る方法](https://github.com/sakura-editor/sakura/wiki/GitHub-Tips:-Markdown-%E3%81%AB%E5%AF%BE%E3%81%97%E3%81%A6%E7%9B%AE%E6%AC%A1%E3%82%92%E4%BD%9C%E3%82%8B%E6%96%B9%E6%B3%95) を更新しました。

- [Markdown TOC](https://marketplace.visualstudio.com/items?itemName=AlanWalk.markdown-toc) で長い間、根本解決がされなかった。
- https://github.com/AlanWalk/markdown-toc/issues/65#issuecomment-513427063 にあるように [Auto Markdown TOC](https://marketplace.visualstudio.com/items?itemName=huntertran.auto-markdown-toc) という別の fork プラグインが作成されて修正されているのを確認しました。

**Comment by m-tmatma** [comment]
解決したので、閉じます。
