### ISSUE TITLE
ヘルプのキーワードが壊れているのを対応する

### ISSUE THREAD

**Issue by berryzplus** [sakura-editor/management-forum#58]
## 提議

とある掲示板に、ヘルプのキーワードが壊れているという報告が上がってました。
ヘルプの目次はたぶんshift-jisです。文字コードの問題なんではないかと。

_Originally posted by @berryzplus in https://github.com/sakura-editor/management-forum/issues/52#issuecomment-450455927_

## 元ネタ(とある掲示板)

527 sage 2018/12/25(火) 20:12:51.89
> おま環かもしれんけど 
> https://ci.appveyor.com/api/buildjobs/jkp7l4iswskaectc/artifacts/sakura-build1422-cbf7c17c-Win32-Release-Exe.zip 
> を解凍して Alt+F1 (ヘルプ) して「キーワード(N)」を 
>  クリックしたときの左側が文字化けしてるね... 
 
 
529 名無しさん＠お腹いっぱい。 2018/12/25(火) 20:41:14.09
> ヘルプワークショップが日本語版じゃないとかいう問題かもね 
>  しらんけど 
 
## 調査状況

現象の確認すらできてないです。
事実なら対応が必要。

**Comment by k-takata** [comment]
https://github.com/sakura-editor/sakura/issues/922 の関連PRによってすでに直っています。
