### ISSUE TITLE
https://sakura-editor.github.io/ にサイト内検索がほしい

### ISSUE THREAD

**Issue by berryzplus** [sakura-editor/management-forum#61]
端的に言うと
 **google のサイト内検索を流用して検索窓を作ってみてはどうか？**
という提案になります。

特にヘルプトピックの検索機能があると、
ユーザにとっての利便性も上がるような気がします。

**Comment by KageShiron** [comment]
過去ログ検索のやり方をそのままヘルプに適用すれば良さそうですね。

https://github.com/sakura-editor/sakura-editor.github.io/blob/c932ae46dd53eaa7bbcd069047a0faaa022ac08d/index.html#L138-L143

（そういえば、現状ではヘルプはchmと同期する的なのは後回しになったままでしたっけ？）

**Comment by m-tmatma** [comment]
https://github.com/sakura-editor/sakura-editor.github.io/pull/50 を送りました。

**Comment by berryzplus** [comment]
対応ありがとうございます :smile:
