### ISSUE TITLE
multifile.exeは現状でも必要？

### ISSUE THREAD

**Issue by KageShiron** [sakura-editor/management-forum#62]
SakuraDownのページを見ていてmultifile.exeというツールを知りました。適当に試して見た感じ、すでに複数ファイルが開けない問題は本体側で解消されているように感じました。

http://sakura.qp.land.to/?cmd=read&page=Install%2Fmultifile.exe

私が勘違いしてるだけでまだ使い道があるなら、公開元のgeocitiesが終了間近なので何らかの形でプロジェクトに取り込みたいです。(プログラムをインストーラに同梱、issueを立てて不具合を消す)

すでに不要となって久しいなら、誤解する人が出ないようにWikiを直しておきます。

**Comment by KageShiron** [comment]
コメントがつかないので、Wikiを非推奨であると書き換えました。追加で情報をお持ちの方がいたら適宜編集をお願いします。

**Comment by ds14050** [comment]
古い Windows では SendTo フォルダに入れたショートカットファイルのプロパティを編集して sakura.exe へのオプション(-TYPE:htm など)を追加しても、ファイルを送ったときには無視されてしまう、というようなことがあったような気がします。おそらくそういう理由で multifile.exe が必要とされていたのだと思いますが、確証がありません。

98SE->XP->Vista と使ってきましたが、XP か Vista からはショートカットファイルのコマンドラインオプションが無視されるということはないようです。では 98SE がどうだったかというと、もう不確かですが。

----

Wiki の内容はあれでいいと思います。過去の記事も読めますし。

**Comment by berryzplus** [comment]
> 古い Windows では SendTo フォルダに入れたショートカットファイルのプロパティを編集して sakura.exe へのオプション(-TYPE:htm など)を追加しても、ファイルを送ったときには無視されてしまう、というようなことがあったような気がします。おそらくそういう理由で multifile.exe が必要とされていたのだと思いますが、確証がありません。

コマンドラインの仕様が結構あいまいなんですよね。

```cmd
sakura.exe -Type:htm aaa.txt -Type:txt bbb.html ccc.plusplus
```

としたときの「どういう結果になるべきか？」の答えを誰も持ってない気がします。
実装は、同じ種類のオプションを指定したら「後勝ち」になるので、3ファイルとも「テキスト」で開くはずです。　←　それが **正解かどうか** が不明。

考えててもしゃーないので、誰かが「これでいきま～す！」と宣言して華々しく散る必要があると思っています。（「散る」の必須。

めんどうなのでまだしばらくはいいかな、と思ってますけど。

**Comment by ds14050** [comment]
自分が書いたのは OS の仕様の変遷であって、sakura.exe が行う解釈のことではありません。Windows が勝手にオプションを捨ててしまっていたんです(たしかそうだった)。

**Comment by KageShiron** [comment]
とりあえず、9x時代ぐらいまでならもう気にしなくて良さそうですね。

コマンドラインの仕様は、別途整理した方が良さそうというのもそうですね。このissueを立てる時にパーサを見に行ったのですが、ゴリゴリ解析していて辛そうでした。最近だと良いパーサライブラリがあるのかな。
