### ISSUE TITLE
WIP (Work In Progress) の GitHub アプリの使用を停止

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/management-forum#63]
WIP (Work In Progress) の GitHub アプリの使用を停止しようと思います。

https://github.com/sakura-editor/management-forum/issues/16 で [WIP (Work In Progress) の GitHub アプリ](https://probot.github.io/apps/wip/) を導入しましたが、利用を停止しようと思います。

https://github.blog/2019-02-14-introducing-draft-pull-requests/ で draft pull requests の機能が対応されたためです。

https://github.com/sakura-editor/sandbox/pull/19 でテスト的に pull request を作成してみました。

**Comment by m-tmatma** [comment]
なお Pull Request の検索時に `is:draft` を指定すると Draft Pull Request をフィルタリングできました。
https://github.com/sakura-editor/sandbox/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+is%3Adraft+

**Comment by m-tmatma** [comment]
https://github.com/sakura-editor/sandbox/pull/20
で draft pull request を作成後、“Ready for review” ボタンを押してみた。
一度通常の pull request に設定後、draft pull request に戻す方法はないみたい。

**Comment by berryzplus** [comment]
approveで。

**Comment by m-tmatma** [comment]
draft pull reuest から普通の pull request にしたあと、draft pull request に戻す方法はないみたいなので、まだ削除せずに残しておきます。

**Comment by m-tmatma** [comment]
https://github.com/sakura-editor/management-forum/issues/79#issuecomment-676782907
により

WIP (Work In Progress) の GitHub アプリの使用
を止めました。

**Comment by berryzplus** [comment]
#79 comment
> 通常のプルリクエストからドラフトプルリクエストにすることはできませんでしたが、できるようになったみたいです

了解です 😄
