### ISSUE TITLE
Azure Pipelines の導入

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/management-forum#65]
Azure Pipelines  を導入しようと思います。

関連
https://github.com/sakura-editor/sakura/issues/446

流れ的には以下のようにしようと思います。

1. sakura editor の ci アカウントで microsoft account を作成する
2. 上記アカウントで azure pipeline 用の organization を作成する
3. [sandbox 用のプロジェクト](https://dev.azure.com/sakuraeditor/sandbox) を作成する
4.  (azure pipelines 上での ) sakura editor organization に対して [sakura editor organization](https://github.com/sakura-editor) に対するアクセス権を付与する。
5. [azure-pipelines.yml](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema) を sandbox に追加して何らかのビルドを行えるようにする。
6.  azure-pipelines で遊ぶ (今ここ)
7. 上記プロジェクトに対して、sakura editor の開発メンバーを招待する。
8.  https://github.com/sakura-editor/sakura に対する導入に関して導入方法を検討する
    (当分の間は appveyor と azure pipelines との併用になると思います)

**Comment by m-tmatma** [comment]
必要な権限は以下です。

<img width="621" alt="スクリーンショット 2019-03-27 4 40 22" src="https://user-images.githubusercontent.com/5567450/55029706-19adc300-504e-11e9-8014-d79a6803d84c.png">

**Comment by m-tmatma** [comment]
関連
https://github.com/sakura-editor/sakura/issues/446

**Comment by m-tmatma** [comment]
https://github.com/sakura-editor/sandbox に対して導入してみました。
メンバーを招待する機能はオーナーしか使えないみたい。
オーナーを追加する機能を調査中。

**Comment by m-tmatma** [comment]
参考サイト
https://srz-zumix.blogspot.com/2018/12/azure-pipelines.html
https://srz-zumix.blogspot.com/2018/12/azure-pipelines_11.html
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=yaml&viewFallbackFrom=vsts

**Comment by m-tmatma** [comment]
@sakura-editor/sakura-developers

appveyor に登録されているメールアドレスに招待メールを送りました。
microsoft アカウントでログインしてください。

**Comment by KENCHjp** [comment]
おお、これでメールが来てたのですね。
周回遅れになりますが勉強します。
仕事方面でもAzureテコ入れしていこうとしてるようなので。

**Comment by takke** [comment]
@m-tmatma さん
> appveyor に登録されているメールアドレスに招待メールを送りました。
> microsoft アカウントでログインしてください。

招待メールが見当たらないのですが takke30 @ gmail.com 宛にいただくことはできますか？

https://dev.azure.com/sakuraeditor/ にアクセスしようとすると 401 になります。

![2019-04-05_10h24_23](https://user-images.githubusercontent.com/73930/55598318-1375c000-578d-11e9-8757-6d8dee4a41a7.png)

**Comment by m-tmatma** [comment]
送りました。

**Comment by m-tmatma** [comment]
ユーザー数に制限があるみたいで、権限を設定しようとすると
有料の契約がいるみたいな感じのメッセージが出ますね。

**Comment by takke** [comment]
> 送りました。

ありがとうございます。無事届きました。

**Comment by m-tmatma** [comment]
> ユーザー数に制限があるみたいで、権限を設定しようとすると
> 有料の契約がいるみたいな感じのメッセージが出ますね。

https://docs.microsoft.com/ja-jp/azure/devops/organizations/billing/buy-basic-access-add-users?view=azure-devops&viewFallbackFrom=vsts

`In this quickstart, you learn how to pay for more users in your organization. You only need to pay for users when your team size exceeds the free limits. It's free to add users who have a Visual Studio subscription. You also get five free additional users in your organization.`

**Comment by berryzplus** [comment]
>In this quickstart, you learn how to pay for more users in your organization. You only need to pay for users when your team size exceeds the free limits. It's free to add users who have a Visual Studio subscription. You also get five free additional users in your organization.

5人までは無料、と書いてある気がします。
visual studioの何らかのサブスクリプションを持つ人も追加料金はかからんみたいですね。
この文章からは、権限付与に費用が必要という情報は読み取れませんでした。
（ってか、参照URL見ろよ、って言われそうですが :smile:

**Comment by berryzplus** [comment]
ああ、課金がいるみたいだけど5人に達してないからまだ大丈夫って共有だったんですね。

**Comment by KENCHjp** [comment]
5人ってどっから来てるんでしょうねぇ。。。せめて１０人にしてほしいなぁ・・・

**Comment by m-tmatma** [comment]
> 5人ってどっから来てるんでしょうねぇ。。。せめて１０人にしてほしいなぁ・・・

以下で質問投げていた。
https://github.com/sakura-editor/sakura/issues/446#issuecomment-480447213

回答返ってきた。
https://github.com/sakura-editor/sakura/issues/446#issuecomment-481261174

> For open source, Pipelines-only usage, you don't need to pay for Basic users. You can use Stakeholder users, which are free and have full access to both Pipelines and administrative functions. Sorry for the confusion.

`Basic` に設定しようとしていたけど、 `Stakeholder` に設定したらいいらしい。

**Comment by m-tmatma** [comment]
Azure Pipelines の yml の編集に便利なプラグインです。
https://marketplace.visualstudio.com/items?itemName=ms-azure-devops.azure-pipelines
https://www.infoq.com/jp/news/2019/02/azure-pipelines-updates

**Comment by m-tmatma** [comment]
さっき azure  pipelines にログインしようとしたら
GitHub アカウントでログイン のボタンが表示された。
まだ試してないけど。

**Comment by m-tmatma** [comment]
GitHub アカウントでログインできた。

1 azure  pipelines に読み取り権限を与えるか確認ダイアログが出る
2 azure  pipelines に GitHub アカウントを関連づけるか確認ダイアログが出る
3 Microsoft アカウントに関連づけている電話に sms を送る
4 送られてきた認識コードを入力する

という流れみたいです

**Comment by m-tmatma** [comment]
`/AzurePipelines run` というコメントを PR に書くことによって、PR のリビルドができます。

- https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#comment-triggers
- https://github.com/sakura-editor/sakura/pull/895#issuecomment-493664689
- https://github.com/sakura-editor/sakura/pull/895#issuecomment-493664734

以下 wiki にも追加しています。
https://github.com/sakura-editor/sakura/wiki/azure-pipelines%E3%83%A1%E3%83%A2#pr-%E3%82%92%E3%83%AA%E3%83%93%E3%83%AB%E3%83%89%E3%81%97%E3%81%9F%E3%81%84%E3%81%A8%E3%81%8D

**Comment by m-tmatma** [comment]
https://github.com/sakura-editor/sakura/pull/886#issuecomment-493667520

`/azp run` と覚えてください。

**Comment by m-tmatma** [comment]
導入してだいぶん経って、特に導入にあたって
残件ないので閉じます。

何か有れば具体なチケットで。
