### ISSUE TITLE
v2.4.0 alpha1 pre-release 確認issue

### ISSUE THREAD

**Issue by KENCHjp** [sakura-editor/management-forum#66]
前のIssueが長くなってきたので新たに立てます。

https://github.com/sakura-editor/management-forum/issues/52

----
コメントで上げられた検討事項

- [x] [「ファイルの排他制御モード」のデフォルトを 「排他制御しない」に変更する by m\-tmatma · Pull Request \#263 · sakura\-editor/sakura](https://github.com/sakura-editor/sakura/pull/263) が治ってない？
- [x] 成果物の ZIP 内部のフォルダを短くする(リリースファイルのファイル名が長すぎるのでは？) 
 -> https://github.com/sakura-editor/sakura/pull/815
- [x] EXE の ZIP に入れるファイルが多いのでは？ -> https://github.com/sakura-editor/sakura/pull/816
- [ ] Webも更新する -> https://github.com/sakura-editor/sakura-editor.github.io/issues/48
- [x] md5ファイル生成も appveyor で自動化したい -> https://github.com/sakura-editor/sakura/pull/829
- [ ] v2.4のヘルプ キーワード検索画面のリストが文字化けしている -> https://github.com/sakura-editor/sakura/issues/922

**Comment by KENCHjp** [comment]
https://github.com/sakura-editor/management-forum/issues/52#issuecomment-477000416
転記。
`sakura-tag-v2.4.0-alpha1-build1699-2582c34c-Win32-Release-Exe.zip` をダウンロードしましたが
このファイルをフォルダ名にして展開すると
`R:\sakura-tag-v2.4.0-alpha1-build1699-2582c34c-Win32-Release-Exe\sakura-tag-v2.4.0-alpha1-build1699-2582c34c-Win32-Release\EXE\sakura.exe`
と `sakura.exe` までのパスが137文字あって長いのは少し対策が必要じゃないか？と思いました。

`R:\sakura-v2.4.0-alpha1-Win32-Release-Exe\sakura-v2.4.0-alpha1-Win32-Release\EXE\sakura.exe`
になったらちょっとマシかな？と思いました。

ちなみにインストーラーだと
`R:\sakura-tag-v2.4.0-alpha1-build1699-2582c34c-Win32-Release-Installer\sakura-tag-v2.4.0-alpha1-build1699-2582c34c-Win32-Release\Installer\sakura_install2-4-0-1699-x86.exe`
EXE ファイルまでのパスが137文字あります。

**Comment by takke** [comment]
早速ありがとうございます。

EXE の ZIP が Installer よりもデカイ(18.6MB)のが気になっていまして、そのままアップロードしていいのか躊躇していました。

sakura.pdb や sakura_lang_en_US.pdb は(debugビルドはともかく)Releaseビルドには不要かなと思うのですがいかがでしょうか。

**Comment by takke** [comment]
> `R:\sakura-v2.4.0-alpha1-Win32-Release-Exe\sakura-v2.4.0-alpha1-Win32-Release\EXE\sakura.exe`
> になったらちょっとマシかな？と思いました。

私もリリース版は sakura-v2.4.0-alpha1-Win32-Release-Exe.zip くらいにリネームしてアップロードでもかまわないと思います。Artifacts へのURLも貼っていただいているのでどのビルドかは追跡できると思いますし。

**Comment by KENCHjp** [comment]
https://github.com/sakura-editor/sakura/pull/263

これが治ってない気がします。
うち的にはこれキラーコンテンツなのでどなたか検証対応をお願いします。
![キャプチャ](https://user-images.githubusercontent.com/39618965/55058644-e56aee80-50af-11e9-9d36-04041824142a.PNG)

**Comment by KENCHjp** [comment]
>sakura.pdb や sakura_lang_en_US.pdb は(debugビルドはともかく)Releaseビルドには不要かなと思うのですがいかがでしょうか。

私も思ったのですが、一旦そのままあげてみました。
releaseビルドに必要なければ、削りたいですね。

**Comment by k-takata** [comment]
> sakura.pdb や sakura_lang_en_US.pdb は(debugビルドはともかく)Releaseビルドには不要かなと思うのですがいかがでしょうか。

Releaseビルドを実行中に起きたエラーを調べるには、Releaseの .pdb も必要だと思います。ただ、同じ .zip ファイルに入れるべきかは疑問です。ついでに、sakura-doxygen.chm/chi も別zipでいいのではないかという気がします。
なお、sakura_lang_en_US.dll には実行コードがないので sakura_lang_en_US.pdb はRelease/Debugともに不要だと思います。

**Comment by KENCHjp** [comment]
ファイル名の長さおよび何を梱包するかについては、ci系手を入れるのが工数かかるようであれば（またはセンシティブであれば）、一旦手動対応でも構わないかなと思っています。
何を梱包するかだけの議論でいいかと思うので。
最悪インストラーのみ公開でも構わないかなと。

**Comment by KENCHjp** [comment]
sakura-tag-v2.4.0-alpha1-build1699-2582c34c-Win32-Release-Installer.zip
sakura-tag-v2.4.0-alpha1-build1699-2582c34c-Win32-Release-Exe.zip

このこらの中のパスが、
\sakura-tag-v2.4.0-alpha1-build1699-2582c34c-Win32-Release\EXE\
\sakura-tag-v2.4.0-alpha1-build1699-2582c34c-Win32-Release\Installer\
がついてるので、まるっと取ってて直下をzip化してもいいかもですね。

**Comment by KENCHjp** [comment]
インストーラーをWindows10(32bit)で、新規インストールアインインストールの動確しました。

**Comment by KENCHjp** [comment]
備忘録
https://github.com/sakura-editor/sakura-editor.github.io
こっちもv2.4.0リリース用のブランチ切る。

**Comment by m-tmatma** [comment]
> [sakura-editor/sakura#263](https://github.com/sakura-editor/sakura/pull/263)
> 
> これが治ってない気がします。
> うち的にはこれキラーコンテンツなのでどなたか検証対応をお願いします。
> ![キャプチャ](https://user-images.githubusercontent.com/39618965/55058644-e56aee80-50af-11e9-9d36-04041824142a.PNG)

これは新規インストールのみです。
アップデートインストールでは、設定値は変更されないので。

**Comment by KENCHjp** [comment]
>これは新規インストールのみです。

新規インストールしたつもりです。

C:\Program Files\sakura

このsakuraフォルダと、

C:\Users\<user>\AppData\Roaming\sakura

このsakuraフォルダが無いのは確認して新規インストールしたのですが、
他にありますでしょうか？

**Comment by KENCHjp** [comment]
起動して、
C:\Users\<user>\AppData\Roaming\sakura\sakura.ini

ここにiniファイルが出来上がってるのを確認して一度落として、iniファイル削除して再度たちあげてもみたのですが。

**Comment by m-tmatma** [comment]
32bit os ですか？
64bit os だとアプリフォルダが違います。

**Comment by m-tmatma** [comment]
32bit os ですか？
64bit os だとアプリフォルダが違います。

**Comment by m-tmatma** [comment]
↑ 書いてた。

**Comment by KENCHjp** [comment]
32bit osです。
VirtulaBoxで32bitのまっさらな環境作って確認中。

**Comment by KENCHjp** [comment]
ああ、ぼちぼち離席します。すいません。

**Comment by m-tmatma** [comment]
> sakura-tag-v2.4.0-alpha1-build1699-2582c34c-Win32-Release-Installer.zip
> sakura-tag-v2.4.0-alpha1-build1699-2582c34c-Win32-Release-Exe.zip
> 
> このこらの中のパスが、
> \sakura-tag-v2.4.0-alpha1-build1699-2582c34c-Win32-Release\EXE
> \sakura-tag-v2.4.0-alpha1-build1699-2582c34c-Win32-Release\Installer
> がついてるので、まるっと取ってて直下をzip化してもいいかもですね。

これは https://github.com/sakura-editor/sakura/pull/114#issuecomment-396964052 で対応したものです。

パスを短くするのは zipartifacts.batをちょこっと変えるだけです。
ただ、私は今日は時間は取れないです。

今日リリースすることにこだわらなくてもいいんじゃないかとは思ってます。
見つかった問題を対処してからリリースする方がいいと思います。

**Comment by KENCHjp** [comment]
すいません、今日releaseにはこだわってないです。
@takke さんが頑張っていただいたので、私もやれる範囲で、一通りreleaseまでやってみようかなって思って手を動かしてみましたが、
まだalpha版なので、こっから1weekぐらいみんなで埃叩いて再来週ぐらいリリース出来たらなってイメージです。
４月中でもいいかなっと。

**Comment by KENCHjp** [comment]
もういっそ新元号にあわせてもいいかなとかか。

**Comment by beru** [comment]
https://sakura-editor.github.io/download.html

こちらのページの更新もリリース作業に加えるのはどうでしょうか？

**Comment by m-tmatma** [comment]
https://github.com/sakura-editor/sakura/releases/tag/v2.4.0-alpha1

にダウンロード数のカウンタつけました。

こんな感じの指定です。

`![Github Releases v2.4.0-alpha1](https://img.shields.io/github/downloads/sakura-editor/sakura/v2.4.0-alpha1/total.svg "v2.4.0-alpha1")
`

**Comment by m-tmatma** [comment]
パス名を短くする PR https://github.com/sakura-editor/sakura/pull/815 を作成しました。
ZIP 内部のフォルダ名に関して、こうしたほうがいいとかあったらコメントください。

**Comment by m-tmatma** [comment]
> ファイル名の長さおよび何を梱包するかについては、ci系手を入れるのが工数かかるようであれば（またはセンシティブであれば）、一旦手動対応でも構わないかなと思っています。

https://github.com/sakura-editor/sakura/pull/815 が終わったら PR 投げます。

**Comment by KENCHjp** [comment]
@m-tmatma さん

>sakura-editor/sakura#815 が終わったら PR 投げます。

了解です！

**Comment by m-tmatma** [comment]
あと、https://github.com/sakura-editor/sakura/milestone/1 の扱いを考える必要があります。

https://github.com/sakura-editor/sakura/releases/tag/v2.4.0-alpha1 を作成していますが、

alpha1 ～ 正式な v2.4.0 までのバージョンの間にいくつか変更が入ると思いますが、
どの修正が alpha1 ～ 正式な v2.4.0 の間に入ったか、わかるようになんらかの形で
管理したいです。

**Comment by KENCHjp** [comment]
@beru さん

>こちらのページの更新もリリース作業に加えるのはどうでしょうか？

もち！

**Comment by KENCHjp** [comment]
@m-tmatma さん

＞どの修正が alpha1 ～ 正式な v2.4.0 の間に入ったか、わかるようになんらかの形で
管理したいです。

ですよね。
正式なv2.4.0とalpha1のタグ付けの間は、Add CHANGELOG.md に再度反映されるかなって考えております。
もしくは、alpha1はあくまで検証で、2.3.0～2.4.0のCHANGELOGでもいいのかなとか。

**Comment by m-tmatma** [comment]
> あと、https://github.com/sakura-editor/sakura/milestone/1 の扱いを考える必要があります。

名前を "next release" から v2.4.0 に変更しました。

**Comment by m-tmatma** [comment]
https://github.com/sakura-editor/sakura/milestone/1 にマイルストーンが設定されているもので
まだ open のものがいっぱいある。

**Comment by KENCHjp** [comment]
releaseのzipファイル作成と同時にmd5ファイルも生成してあると捗りますね。

certutil -hashfile D:hoge.exe MD5

はまるのは最後のハッシュ アルゴリズムがちゃんと大文字じゃないとダメってところ・・・

**Comment by KENCHjp** [comment]
一応「カンバン」も作ってありますが、「カンバン」を運用するのも二重メンテな感じがするので、今後はこういうIssueで廻した方がいいかなと、思い始めております（ほぼ独り言）

**Comment by m-tmatma** [comment]
忘れないように書いておきます。
正式リリースのときは changelog.md を wiki に貼り付けるのも必要です。

**Comment by m-tmatma** [comment]
> releaseのzipファイル作成と同時にmd5ファイルも生成してあると捗りますね。
> 
> certutil -hashfile D:hoge.exe MD5
> 
> はまるのは最後のハッシュ アルゴリズムがちゃんと大文字じゃないとダメってところ・・・

これはローカル生成ですか？
それならこれも appveyor で自動化したい

**Comment by KENCHjp** [comment]
>これはローカル生成ですか？

alphaは手動ですが自動化したいっす。

**Comment by m-tmatma** [comment]
appeyor  で sha 系のハッシュをすでに生成してたような気がします。

**Comment by takke** [comment]
> 忘れないように書いておきます。
> 正式リリースのときは changelog.md を wiki に貼り付けるのも必要です。

これって [CHANGELOG.mdスナップショット](https://github.com/sakura-editor/sakura/wiki/CHANGELOG.md%E3%82%B9%E3%83%8A%E3%83%83%E3%83%97%E3%82%B7%E3%83%A7%E3%83%83%E3%83%88) のことですか？それとも古い wiki ですか？
(リリース手順に追記しようと思いまして)

**Comment by KENCHjp** [comment]
>appeyor で sha 系のハッシュをすでに生成してたような気がします。

各々のファイル単位でしたっけ？

**Comment by takke** [comment]
@KENCHjp さん
> 備忘録
> https://github.com/sakura-editor/sakura-editor.github.io
> こっちもv2.4.0リリース用のブランチ切る。

@beru さん
> https://sakura-editor.github.io/download.html
> こちらのページの更新もリリース作業に加えるのはどうでしょうか？

いずれも同じように Web の更新のことをさしてますよね。
取り急ぎ、[リリース手順のWiki](https://github.com/sakura-editor/sakura/wiki/%E3%83%AA%E3%83%AA%E3%83%BC%E3%82%B9%E6%99%82%E3%81%AB%E3%82%84%E3%82%8B%E3%81%93%E3%81%A8) に追記しました。

Webだしわざわざv2.4.0リリース用のブランチ切らなくても、、と思ったんですがダウンロードページはだいぶ古いので全面的に書き換える必要があるんですね。
Web の更新は https://github.com/sakura-editor/sakura-editor.github.io/issues/48 を立てたのでこちらで議論したいです。

**Comment by m-tmatma** [comment]
2.4.0 の alpha 1 用のページ、alpha 2 用のページ、正式版のページとリリース毎に作ったらいいと思います。

**Comment by takke** [comment]
> 2.4.0 の alpha 1 用のページ、alpha 2 用のページ、正式版のページとリリース毎に作ったらいいと思います。

えーっと、これは wiki の CHANGELOG のことですか？

**Comment by KENCHjp** [comment]
>appeyor で sha 系のハッシュをすでに生成してたような気がします。

https://github.com/sakura-editor/sakura/blob/master/appveyor.md

ここに説明ありましたね。
sha256.txtってファイルが出来るように見えるのですが、appveyorの成果物から見つけられず・・・

**Comment by m-tmatma** [comment]
> > 2.4.0 の alpha 1 用のページ、alpha 2 用のページ、正式版のページとリリース毎に作ったらいいと思います。
> 
> えーっと、これは wiki の CHANGELOG のことですか？

そうです。
そうすればどの alpha でどの機能をいれたか追跡可能でかつ、生成を
自動かできて楽かと思います。

**Comment by m-tmatma** [comment]
>     * md5ファイル生成も appveyor で自動化したい

コマンドラインでやる方法はいっぱいあるけど、ハッシュだけ出力はないのだろうか?
https://www.atmarkit.co.jp/ait/articles/0507/30/news017.html

https://docs.python.org/ja/3/library/hashlib.html を使えば python でも書けるが。

**Comment by m-tmatma** [comment]
> https://docs.python.org/ja/3/library/hashlib.html を使えば python でも書けるが。

既存の sha256.txt は hashlib を使って calc-hash.py で生成している。

**Comment by takke** [comment]
> > > 2.4.0 の alpha 1 用のページ、alpha 2 用のページ、正式版のページとリリース毎に作ったらいいと思います。
> そうすればどの alpha でどの機能をいれたか追跡可能でかつ、生成を
> 自動かできて楽かと思います。

現状の changelog-sakura の設定だと、タグを打った時刻で区切って Issue/PR が抽出されるので、そのままでも alpha1 と alpha2 ～ 正式版のそれぞれの修正が載ることになります。

例えば Release/v2.4.0-alpha1 タグを打った後に閉じた[リリース作業のPR #814](https://github.com/sakura-editor/sakura/pull/814) は、今朝生成された CHANGELOG.md には Unreleased すなわち alpha2 相当のところに載っています。
(https://github.com/sakura-editor/sakura/pull/814 自体は management ラベルを付けたので次回からは抽出されなくなりますけど)

![2019-03-29_00h24_40](https://user-images.githubusercontent.com/73930/55170027-2c90d680-51b9-11e9-98a8-5a4db88968a0.png)

CHANGELOG.md には alpha1 等は含めず、正式版の分だけ載せるほうがいいですかね。そうであれば CHANGELOG.md のコミット前の整形がもうひと手間必要になりますね。

**Comment by KENCHjp** [comment]
OS標準ではいっているので、certutilつかうのがハッシュ値とるだけならいいのかなと。

**Comment by m-tmatma** [comment]
> > sakura.pdb や sakura_lang_en_US.pdb は(debugビルドはともかく)Releaseビルドには不要かなと思うのですがいかがでしょうか。
> 
> Releaseビルドを実行中に起きたエラーを調べるには、Releaseの .pdb も必要だと思います。ただ、同じ .zip ファイルに入れるべきかは疑問です。ついでに、sakura-doxygen.chm/chi も別zipでいいのではないかという気がします。
> なお、sakura_lang_en_US.dll には実行コードがないので sakura_lang_en_US.pdb はRelease/Debugともに不要だと思います。

https://github.com/sakura-editor/sakura/pull/816

**Comment by m-tmatma** [comment]
サクラエディタ側、web 側ともに release ブランチの protect 設定しました。

<img width="824" alt="protect3" src="https://user-images.githubusercontent.com/5567450/55269304-082a1c80-52d5-11e9-98c6-0f04fe5c6cfe.png">

<img width="829" alt="protect4" src="https://user-images.githubusercontent.com/5567450/55269311-2ee85300-52d5-11e9-804d-a8827b0f5542.png">

**Comment by KENCHjp** [comment]
このIssueで決めてた方がいい気がしてきたのですが、2.4.0リリース直後に、一旦バージョンを2.4.1にして、マジリリースしようとするときに、2.4.1でいいくのか、2.5.0にするのか再協議って運用どうでしょう。

**Comment by m-tmatma** [comment]
https://github.com/sakura-editor/sakura/milestone/2
v2.4.0 以降にいれるための Milestone を作成しました。
 v2.4.0 には入れないことを明示して目標スケジュールの共有に使用ください。

**Comment by arigayas** [comment]
v2.4.0 リリースにあたって次のリリース（アルファ2かベータ1）を作成されないのでしょうか？

_GitHubに移行して1年以内にv2.4.0がリリースされるのが良いと思っております。_

**Comment by KENCHjp** [comment]
@arigayas さん　コメントありがとうございます。
今見つかってるクリティカル不具合（と私がリクエストしたもの）修正と他の方からの動確あつまったら、alpha2かベータ1リリースをしたいとおもっておりますが、本プロジェクトは強制しないのがモットーかと思っておりますので、旗振り力＆誘導力弱い私めはひとまずAzure対応を追いかけ中でございます。

正式リリースを２０周年でだせるといいよねとか、桜の日にリリースできればいいよねとか、一瞬もりあがりましたがこればっかりはメンバーの都合というかパワー次第かと。
気長にお待ちいただければ幸いです^^;

**Comment by arigayas** [comment]
ユーザーは、のんびり待つしかないのですね(´；ω；`)

**Comment by berryzplus** [comment]
> 「ファイルの排他制御モード」のデフォルトを 「排他制御しない」に変更する by m-tmatma · Pull Request #263 · sakura-editor/sakura が治ってない？

win8.1 pro 64bit, win10 pro 64bit で「再現なし」を確認しました。

再現環境が残っていたら `sakura.ini` 内の `nFileShareMode` の値がどうなってるか調べてみてほしいです。予想では `=1` になっているはず。（コード的には =0 を書くように変更してます。）

**Comment by KENCHjp** [comment]
＞win8.1 pro 64bit, win10 pro 64bit で「再現なし」を確認しました。
お、ではもう一度確認してみます。
再現方法は、常駐していないことを確認したのち、iniファイルを消して起動、なのですが、あってますでしょうか。

**Comment by berryzplus** [comment]
> 再現方法は、常駐していないことを確認したのち、iniファイルを消して起動、なのですが、あってますでしょうか。

手順は、①`sakura.exe` と同じフォルダに `sakura.ini` がないこと、②起動中の `sakura.exe` がないことを確認したのち、③`sakura.exe` を起動、④共通設定で「排他制御しない」を確認、⑤「サクラエディタの全終了」をさせてから⑥`sakura.ini`を開いて`nFileShareMode`の値を確認、でした。

こちらでも HyperV のOSイメージをダウンロードして再現テストしてみます。

確か既出だと思いますが、MSがEdgeブラウザのテスト用に無償イメージを提供してるみたいですね。
https://eng-notebook.com/post-2199/

----

`sakura.exe.ini` の設定によって挙動が変わることに、今気付きました。
インストーラーはどう制御しているんでしたっけ・・・（詳細は調べてみてから書きます。

**Comment by berryzplus** [comment]
Win7 32bitで「再現なし」を確認しました。

先述blog記事のリンク先にあった `IE11 - Win7(x86)` の `VirtualBox` 版を使いました。
(Hyper-V版は動かなかったのでVirtualBox落としてきて入れました:smile:)
英語OSのまま、D&Dでinstaller.zipをコピって検証してみました。
[Win32 Releaseのインストーラー版](https://github.com/sakura-editor/sakura/releases/tag/v2.4.0-alpha1)で日本語にし、オプションはデフォルトのままインストールしました。

初回起動で `not exclusive` になっていること、
初回起動の終了時に常駐アイコンが残らないことが確認できました。

`sakura.exe.ini` はデフォルトで「個人用設定にする」だったみたいです。チェックを外してUACに弾かれたとしても、初期設定が反映されないようには見えない（設定が読めないと「排他制御なし」になる）ので原因は別っぽい気がしました。

**Comment by KENCHjp** [comment]
@berryzplus さん　確認どうもです。
私も追試します。お手数おかけします。

**Comment by KENCHjp** [comment]
別PCがあったのでEXEを展開して確認しましたが、再現しませんでした（ただしく動作します）
私の確認方法に問題があったか環境に何が問題があるようなので、一旦私の確認ミス(おま環)ということにさせてください。
皆様お手数おかけしてすいません。

あとは特に不具合的なの発生してないということですかね。

一件、　
https://github.com/sakura-editor/sakura/issues/909
こういうのはありましたが。
ぼちぼちベータ？

**Comment by takke** [comment]
> あとは特に不具合的なの発生してないということですかね。

現時点でダウンロード数も798ありますし、alpha版にしては割とたくさん使われているような気がします。

![2019-05-17_13h24_02](https://user-images.githubusercontent.com/73930/57903013-0c22f580-78a7-11e9-9096-ac90a7037b09.png)

そろそろ beta1 ですかね？

**Comment by KENCHjp** [comment]
releaseバイナリをAzureからにするのかな？、AppVeyorでいいのかな。
正直どっち(AzureとAppveyor)が何の役割になっているか、追い切れてなくて^^;
シーケンス図っぽいのあると嬉しいかな。

**Comment by takke** [comment]
Azure-Pipelines は AppVeyor よりも速い(並列ビルドができる)し、柔軟な設定が出来たり比較的分かりやすいUIだったりするので皆さんの好みのような気がしています。「お試しで使ってみたら案外良かった」という感想を皆さん持たれてるんじゃないですかね。

ただ、現時点では https://github.com/sakura-editor/sakura/issues/821 が完了していないので(かな？)、Azure-Pipelines の成果物のフォルダ名が `sakura-buildLocal-Win32-Release-Installer` になっていたりバージョン番号にビルド番号が含まれないなど、暫定的な対応が残っている状況ですよね。

というわけで今リリースするならまだ AppVeyor からですね。
(Azure-Pipelines と AppVeyor の使い分けについて一度別途Issueで整理したほうが良さそう？)

**Comment by KENCHjp** [comment]
@takke さん了解っす。
Web修正しなくっちゃですね、バッサリ過去を捨てるか、最低限だけ修正するかどうしようかなと。。。

**Comment by m-tmatma** [comment]
https://github.com/sakura-editor/sakura/issues/906 を修正する必要があります。

**Comment by KENCHjp** [comment]
v2.4のヘルプ キーワード検索画面のリストが文字化けしている
https://github.com/sakura-editor/sakura/issues/922

追記しました。pre-releaseと最近のappveyorの成果物見ましたが化けてる模様。

**Comment by KENCHjp** [comment]
長くなったので次立てました。
https://github.com/sakura-editor/management-forum/issues/72
こっちはクローズします。
