### ISSUE TITLE
AppVeyorアカウントの共同運用

### ISSUE THREAD

**Issue by kobake** [sakura-editor/management-forum#7]
現在運用している AppVeyor ビルドについては [sakuraeditor という名前のアカウントを作り、それで運用しています](https://ci.appveyor.com/project/sakuraeditor/sakura)が、今のところこのアカウントを直接操作できるのは自分だけです。
(関連: https://github.com/sakura-editor/sakura/issues/15)

このアカウントの操作を自分以外の人でもできるようにしておきたいのですが、どのような管理をするのが良いでしょうか。

ちなみに AppVeyor の sakuraeditor アカウントのメールアドレスは実は最初から複数人運用を見据えて `sakura-editor-admins@lists.osdn.me` というメーリングリストのアドレスで登録してあります。今このMLに入っているのは kobake 1人だけです。

## 運用者を誰にするかの選択肢
- kobake 1人だけで運用を続ける … ※これだと自分1人が単一障害点になるので避けたい
- kobake を入れて2～3人くらいでいじれるようにする
- コアメンバー全員いじれるようにする
- その他（何かあれば）

## どのようにアカウントを共有するかの選択肢
- なんらかのプライベート連絡手段で「パスワード」を共有する
- その他（何か手段ありますかね）

## ご意見やアドバイス等いただけると助かります
よろしくお願い致します。

**Comment by KENCHjp** [comment]
とりあえず、信頼してないとかじゃなくて、変にいじれる人を増やすと責任を押し付ける感じになりそうなので、私と二人ですかねぇ、とりあえず。
権限与えられると使い方覚えとかないといけないですしね。

こういうの管理するのが苦にならない方とかチャットはだれだれ、OSDNは私とかって役割”分散”でもいいですけど。
Adminもう一人いて３人体制ならバランス的にはちょうどいいかんじかなぁと思うんですが(笑)

**Comment by KENCHjp** [comment]
パスワードはDMですかね。

**Comment by kobake** [comment]
「責任を持ちたくないから権限いらないです」って人もいるでしょうね（とても分かる）

**Comment by m-tmatma** [comment]
アカウント共有しなくてもチームの設定をしたら
いけるのかもしれないです。
https://www.appveyor.com/docs/team-setup/

**Comment by kobake** [comment]
おお、帰ったら見てみます

**Comment by m-tmatma** [comment]
試してみました？

**Comment by kobake** [comment]
すみません、まだ時間とれてなかったです。もうちょっと余裕のあるときに・・・

**Comment by kobake** [comment]
対応遅くなりましたが、さきほど @KENCHjp さんを sakuraeditor アカウントへの Collaborator として招待してみました。

**Comment by KENCHjp** [comment]
仕組みがよくわかってませんが、とりあえず、なんでもできます。
(~^~)!

**Comment by m-tmatma** [comment]
> その他（何かあれば）

全員がビルドの開始 (rebuild) とビルドのキャンセルをできるようにしておきたいです。

**Comment by KENCHjp** [comment]
■変更前 
![1](https://user-images.githubusercontent.com/39618965/43026735-fea39ca2-8cb1-11e8-8d9a-a262618846c5.PNG)
---
■変更後 
![2](https://user-images.githubusercontent.com/39618965/43026737-0022e4a2-8cb2-11e8-832e-d5c88a6e43d3.PNG)
---
パーミッションがこれだけだったのですが、キャンセルもできるのかな・・・

**Comment by m-tmatma** [comment]
ユーザーを追加してから、権限を設定するのだと思います

**Comment by KENCHjp** [comment]
![1](https://user-images.githubusercontent.com/39618965/43028399-bd98c13e-8cba-11e8-9f6a-9e740ff4652b.PNG)

やっとTeamの画面に到達^^;
なぜか私の名前が無いのは仕様なのかな？？

@m-tmatma さん、ここからいったんUser権限でADD COLLABORATORしていいっすか？(メアドは、GitHub掲載のメアドでいいっすよね？）
（一番精通されてるので、ご迷惑でなければAdmin権限でもいいかと思っておりますが）

**Comment by m-tmatma** [comment]
大丈夫です

**Comment by KENCHjp** [comment]
@m-tmatma さん、Admin RoleでADD COLLABORATORしてみました。

**Comment by m-tmatma** [comment]
PR のリビルドとキャンセルができるのを確認しました。

**Comment by KENCHjp** [comment]
すいません、m-tmatmaさんとのやり取り途中で、某さんのメアド記載された画像が入っちゃったのでこの４つ前の私の発言けしちゃいました。

m-tmatma さんへ、AppVeyor一番精通されてるので、ご迷惑でなければAdmin RoleでAddしてもいいですかって、書き込んで「大丈夫です」とのお返事いただいた下りを削除しております。

失礼しました。

**Comment by m-tmatma** [comment]
appveyor の sakuraeditor アカウントに @beru  さんと @berryzplus さんを 追加しませんか?

**Comment by KENCHjp** [comment]
やってみます。

**Comment by beru** [comment]
お気遣いありがとうございます。追加していただけるとリトライが出来るので助かります。

**Comment by KENCHjp** [comment]
ごめんなさい、オペミスしてしまったようで、私が削除されてしまいました。。。
@m-tmatma さん、私と皆さんをお誘いできますか？

**Comment by m-tmatma** [comment]
@KENCHjp さん、@beru さんと @berryzplus さんに招待メールを送りました。
@KENCHjp さんは管理者で @beru さんと @berryzplus さん はユーザー権限にしました。

**Comment by KENCHjp** [comment]
お手数おかけします。

**Comment by KENCHjp** [comment]
https://ci.appveyor.com/profile

ここには、ちゃんと、sakuraeditor Administratorと表示されるのですが、

https://ci.appveyor.com/projects

ここに表示されないのはなぜだろうと調べ中・・・

**Comment by m-tmatma** [comment]
> https://ci.appveyor.com/profile
> 
> ここには、ちゃんと、sakuraeditor Administratorと表示されるのですが、
> 
> https://ci.appveyor.com/projects
> 
> ここに表示されないのはなぜだろうと調べ中・・・

Collaborators のところで招待メールを送ったのですが、
Users の箇所でも招待メールを送ってみました。

**Comment by KENCHjp** [comment]
ありがとうございます。表示されるようになりました。

**Comment by m-tmatma** [comment]
@sakura-editor/sakura-developers 全体にアクセス権を設定をつけられるみたいだったので付与してみました。

<img width="1065" alt="appveyor-team" src="https://user-images.githubusercontent.com/5567450/45585578-a1897680-b921-11e8-832a-0187b91a0f54.png">

**Comment by m-tmatma** [comment]
参考
https://www.appveyor.com/docs/team-setup/#understanding-relationship-between-github-team-and-appveyor-role

**Comment by m-tmatma** [comment]
github  のチームを直接、appeyor のアクセス権をつけられることが確認、運用できているので
閉じます
