### ISSUE TITLE
v2.4.0 alpha1 pre-release 確認issue 2

### ISSUE THREAD

**Issue by KENCHjp** [sakura-editor/management-forum#72]
前のIssueが長くなってきたので新たに立てます。

https://github.com/sakura-editor/management-forum/issues/52
https://github.com/sakura-editor/management-forum/issues/66
----
コメントで上げられた検討事項

- [x] [「ファイルの排他制御モード」のデフォルトを 「排他制御しない」に変更する by m\-tmatma · Pull Request \#263 · sakura\-editor/sakura](https://github.com/sakura-editor/sakura/pull/263) が治ってない？
- [x] 成果物の ZIP 内部のフォルダを短くする(リリースファイルのファイル名が長すぎるのでは？) 
 -> https://github.com/sakura-editor/sakura/pull/815
- [x] EXE の ZIP に入れるファイルが多いのでは？ -> https://github.com/sakura-editor/sakura/pull/816
- [ ] Webも更新する -> https://github.com/sakura-editor/sakura-editor.github.io/issues/48
- [x] md5ファイル生成も appveyor で自動化したい -> https://github.com/sakura-editor/sakura/pull/829
- [x] v2.4のヘルプ キーワード検索画面のリストが文字化けしている -> https://github.com/sakura-editor/sakura/issues/922
- [x] https://github.com/sakura-editor/sakura/pull/940 を revert する
- [ ] sakura リポジトリの HTML のヘルプ (help\sakura\_RESOURCE) を help に取り込む -> https://github.com/sakura-editor/sakura-editor.github.io/issues/47

**Comment by m-tmatma** [comment]
https://github.com/sakura-editor/sakura/pull/940
の revert も必要。

HTML の UTF8 対応を元に戻すのを元に戻す

**Comment by m-tmatma** [comment]
https://github.com/sakura-editor/management-forum/issues/66#issuecomment-493597332

> [sakura-editor/sakura#906](https://github.com/sakura-editor/sakura/issues/906) を修正する必要があります。

に関しては https://github.com/sakura-editor/sakura/pull/967 で workaround としてビルドしないようにしている。
(https://github.com/sakura-editor/sakura/issues/906#issuecomment-513516261)

**Comment by KENCHjp** [comment]
alpha1はリリースしたので、こちらは閉じます。
#75 へ引継ぎます。
