### ISSUE TITLE
v2.4.0 リリース後作業

### ISSUE THREAD

**Issue by KENCHjp** [sakura-editor/management-forum#77]
- [x] sakura-editor / sakura のmasterのバージョンをv2.4.1へ修正。 https://github.com/sakura-editor/sakura/pull/1231
- [x] リリース用手順(wiki)の修正。
- [x] LICENSE ファイルのコピーライトを2020年にする。
- [x] pre-release(alpha,beta)の取り扱いを決める（消す？）
       →残す。

**Comment by KENCHjp** [comment]
＞pre-release(alpha,beta)の取り扱いを決める（消す？）

pre-releaseを残したままのプロジェクトってないと思うので消す方向でいいのかなと思っているのですが、
GUIでTag（Release）は消せないみたい。

リリースを非表示とかにできるかと思ったら出来なさそう。

モジュール自体はどっかに保管しますか？（OSDNなら保管できそうです）

**Comment by KENCHjp** [comment]
＞リリース用手順(wiki)の修正。

こっちについては、Beta3の所にも書きましたが、
```
最初にリリース名でブランチ作成、
今回で言うと、
release/v2.4.0
でタグを、「v2.4.0-beta1」等で打って、
不具合等あれば、master側で修正後、リリースブランチrelease/v2.4.0へマージして
「v2.4.0-beta2」のタグ打ち。
以降何かあればmaster側の修正をマージしてbetaの版数を増やすを繰り返し、
最後にヘルプ他リリース日等を修正して「v2.4.0」のタグ打つって感じでどうでしょう。
```
こんな感じにしようかなと、ブランチがbetaリリースの度に増えてくのもなぁと思いまして。

**Comment by k-takata** [comment]
> pre-releaseを残したままのプロジェクトってないと思うので

そんなことはないと思います。（消してもいいですけど）

ところで、なんか余計なタグが3つほどできていますね。
test/merge-PR1128-PR1127, release/issue1125-test-2.4.0-test2, release/issue1125-test-2.4.0-test
(これか https://github.com/sakura-editor/sakura/pull/1127#issuecomment-570463156)

**Comment by KENCHjp** [comment]
>そんなことはないと思います。（消してもいいですけど）

そうなんすね、ダウンロードページがとっ散らかってるように見えないかなと思ったのですが、
ただpre-releaseを非表示って出来なさそう（タグを消すしかなさそう）なので、チェンジログの出方も変わっちゃいますし、皆さん異論無ければこのままにしましょうか。
OSDN側への転載は正式リリースのみにしてみます。

＞ところで、なんか余計なタグが3つほどできていますね。

issue番号等もわかるので特に作った方のお任せいっかなぁと、がちがちにしないのがここのポリシー(笑)

**Comment by KENCHjp** [comment]
＞＞ところで、なんか余計なタグが3つほどできていますね。
＞issue番号等もわかるので特に作った方のお任せいっかなぁと、がちがちにしないのがここのポリシー(笑)

あ、僕が間違って作ってたのなら消します（今から調べます）

**Comment by KENCHjp** [comment]
>あ、僕が間違って作ってたのなら消します（今から調べます）

私じゃないみたいですね、ひとまず放置で。ChangeLogがTagを拾っちゃうので、消す感じっすかねぇ。

タグあっても自動でリリースにはのっかってこないんですね。。。

**Comment by m-tmatma** [comment]
> ところで、なんか余計なタグが3つほどできていますね。
> test/merge-PR1128-PR1127, release/issue1125-test-2.4.0-test2, release/issue1125-test-2.4.0-test
> (これか [sakura-editor/sakura#1127 (comment)](https://github.com/sakura-editor/sakura/pull/1127#issuecomment-570463156))

消しました。

**Comment by KENCHjp** [comment]
あと

＞　sakura-editor / sakura のmasterのバージョンをv2.4.1へ修正。

これっすね。

＞　リリース用手順(wiki)の修正。

こっちはおいおいやりますです。

**Comment by m-tmatma** [comment]
CHANGELOG.md って公開しました?

**Comment by KENCHjp** [comment]
> CHANGELOG.md って公開しました?

ああ、まだだｗ
やりまーす。

**Comment by KENCHjp** [comment]
PR 立てました< CHANGELOG.md

あと、Projects閉じました。Projects(カンバン)は結局二重管理になってしまうのであんまりこのチームでは運用なじまないかもですね。

**Comment by KENCHjp** [comment]
こっち閉じます。

**Comment by takke** [comment]
[リリース時にやること · sakura\-editor/sakura Wiki](https://github.com/sakura-editor/sakura/wiki/%E3%83%AA%E3%83%AA%E3%83%BC%E3%82%B9%E6%99%82%E3%81%AB%E3%82%84%E3%82%8B%E3%81%93%E3%81%A8) に「リリース後の作業」を追加しておきました。

**Comment by KENCHjp** [comment]
あざまーす。
