### ISSUE TITLE
v2.4.0 beta pre-release 確認issue2

### ISSUE THREAD

**Issue by KENCHjp** [sakura-editor/management-forum#78]
#75 続き。
コメント数が多くなったので別Issue立てました。

**Comment by berryzplus** [comment]
Grep の除外指定の件は、制約事項にリストされてたと思うのでスルーで良いと思っています。

当面の問題を解消する方法は既に提示済みですが、高度すぎて(？)誰もレビュー出来なかった認識です。アレを理解するには何が問題なのかを把握する必要があって、誰でも分かるように説明するのはしんどいんです。その意味でも　@m_tmatma さんにレビューして欲しかった… :cry:

アレを納得行く感じにカスタムしてもらえば、ぼくはたぶんレビュー可能です。

この2年でだいぶ丸くなったので、よっぽど無関係な変更を含めない限り指摘スルーでapproveとすると思います。

**Comment by KENCHjp** [comment]
＞Grep の除外指定の件は、制約事項にリストされてたと思うのでスルーで良いと思っています。

了解。 @m-tmatma さんがよければ、このままリリースへ、やっぱり直したいと言われれば、Beta5行こうと思います。

タグジャンプの件もありますし、来月どうするか考えますかね。

**Comment by KENCHjp** [comment]
https://github.com/sakura-editor/sakura/pull/1210

とりあえずこれウォッチしてます。

**Comment by berryzplus** [comment]
#1210 マージしました。

順番的に次は #1172, #1179 で上がってるソースコードのスタイル問題を解決するために `clang-format` の暫定標準（？）を決めに行く感じかと思っています。
https://yasuharu519.hatenablog.com/entry/2015/12/13/210825

スタイルを強制される、と考えたら嫌ですが、
いい感じに整形してくれると考えたら嫌ってほどでもないかな、と。

スタイル対応はソースは大きく変わるけど機能は変わらない系なので、リリース作業再開しちゃって構わないと思います。

**Comment by KENCHjp** [comment]
＞リリース作業再開しちゃって構わないと思います。

了解、今週末Beta5行きます。これでスリープできれば、そのままリリースへ。

**Comment by berryzplus** [comment]
ラベルの見切れ修正完了。

**Comment by KENCHjp** [comment]
Beta5リリースしました。
![キャプチャ](https://user-images.githubusercontent.com/39618965/77221908-7d9b9680-6b91-11ea-930d-931f61d9459c.PNG)
4月に正式リリース行けるかなぁ。。。

**Comment by KENCHjp** [comment]
2020/04/04リリース目標にしよっかなと思っとります。
ちょっと早いかもですが、Beta5まで来ちゃってますし。

**Comment by KENCHjp** [comment]
あと、ヘルプですが、
```
<center>サクラエディタ   Ver 2.4.0 (開発版)</center>
```
これは、
```
<center>サクラエディタ   Ver 2.4.0</center>
```
こうかな？(過去は↑）
それとも、Chromeとか見てるとOfficial Buildとか書いてあるので、
```
<center>サクラエディタ   Ver 2.4.0 (Official Build)</center>
```
とか、
```
<center>サクラエディタ   Ver 2.4.0 (公式版)</center>
```
とかかな？

**Comment by berryzplus** [comment]
開発版に対して何か？って考えたら
リリース版
になるのかなぁ。

突然英語になるのは「ん？」って感じです:smiley:

もちろん、開発版をdevelopにするなら英語でもいいっす。

OfficialよりはPublicなのかな？

一般向けリリースをGAという表記にしてるのもよく見かけるような。

**Comment by KENCHjp** [comment]
GAもいいですが「リリース版」がしっくりきました。
異論がなければ「リリース版」でいきましょう。

**Comment by KENCHjp** [comment]
あ、でも、「リリース版をリリースしました」ってなんか変かな。。。

**Comment by berryzplus** [comment]
v2.4.0 に GA は付けられんと思っとります。

「リリース出来る」よりも「GA版に出来る」のがハードル高い気がしていて…まぁそんな感じです:sob:

**Comment by KENCHjp** [comment]
まぁ、あれか、過去を踏襲して、何もつけないがいいかな。

**Comment by KENCHjp** [comment]
今週末リリースはちょいとコロナでバタバタしとりまして、もうちょっと先にしようかと思っておりますが、今月中にはしようかと思います。
４／１８狙いで。

**Comment by KENCHjp** [comment]
リリース作業進行中です。
![キャプチャ](https://user-images.githubusercontent.com/39618965/79677546-8386a500-822d-11ea-9199-06b6aa11666a.PNG)

とりあえずインストーラモジュール動確しました。
次リリースファイルアップロード＆ホームページ修正します。

**Comment by KENCHjp** [comment]
リリースファイルアップロード＆ホームページ修正完了したので。
このIssue閉じます。
OSDNへは私がアップロードします。
お疲れ様です。
sakura-editor / sakura のmasterのバージョンをv2.4.1へどなたか修正おなしゃす。
