### ISSUE TITLE
ツールバーの折り返しが効かない

### ISSUE THREAD

**Issue by Suzakura** [sakura-editor/management-forum#83]
最新版「v2.4.1.2849 32bit」にアップデートしました。
ところが、ツールバーの「折り返しバー」が無効になってしまって、登録されたツールバーアイコンが一列にざっと並んでしまっている状態です。

「折り返しバー」を設置するとアイコンを表示するためのスペースはちゃんと一段分下にできています。
図の赤丸の部分が本来なら折り返されて下の段に表示されるはずだったアイコンです。

![キャプチャ](https://user-images.githubusercontent.com/1965971/87112544-12dcab00-c2a7-11ea-8055-f4dd8a12b47f.PNG)

修正または対処方法を教えて頂けますでしょうか？

**Comment by berryzplus** [comment]
これと別件でしょうか？
https://github.com/sakura-editor/sakura/issues/1313
<img alt="sakura" src="https://user-images.githubusercontent.com/3253151/87114566-e0817c80-c2ab-11ea-816a-9191939b60c6.png" width="600"/>

申し訳ないのですが、そういう使い方してる人がメンバーにいないようで、検出できていませんでした。

対処済みの現象と別件であれば、原因調査と対策を行っていきたいと思います。

**Comment by Suzakura** [comment]
berryzplusさま、返信ありがとうございます。

一緒なような違うような…。希望の場所で折り返さない何も、そもそもが折り返しがなされていませんし…。
ちなみにこの対象済みのサクラエディタを試すにはどうすれば良いですか？


あと。ついでに追加報告しておきます。
現在、ツールバーに「検索（ボックス）」を設置しているのですが、これが設置されているとツールバーアイコンの配置が乱れてしまうようです。
具体的には、先ほど投稿した図の「検索（ボックス）」が表示されている辺り、あそこに「新規作成」や「開く（ドロップダウン）」「上書き保存」などのアイコンが隠れているしまっている＆「折り返しバー」前後に妙な空間（「検索（ボックス）」表示分の空間？）が出来ている状態です。

![キャプチャ](https://user-images.githubusercontent.com/1965971/87114365-576a4580-c2ab-11ea-93c4-dacda4eab501.PNG)

こちらはツールバーから「検索（ボックス）」を削除した状態です。
相変わらず「折り返しバー」は機能していませんが、「検索（ボックス）」を削除したことによりレイアウト崩れは解消されているようです。

ついでに旧環境の画像も参考として添付しておきます。

![キャプチャ](https://user-images.githubusercontent.com/1965971/87116176-1294dd80-c2b0-11ea-9936-a5784760134b.PNG)

**Comment by Suzakura** [comment]
最新デバッグ版と思われる「サクラエディタ   v2.4.2.2904 32bit DEBUG」をインストールしてみました。以下がその画面になります。

![キャプチャ](https://user-images.githubusercontent.com/1965971/87118699-019b9a80-c2b7-11ea-9a0a-e08bbd3d7912.PNG)

ツールバーの折り返しは機能するようになりましたが、まだ「検索（ボックス）」が本来の場所に表示されていません。

修正のご検討をよろしくお願いいたします。

**Comment by Suzakura** [comment]
sakura-editor/sakura#1343
▲新たなバグとしてこちらの方に報告させて頂きましたので、一旦ここは閉じさせていただきます。
